### ISSUE TITLE
support of backlog configuration

### ISSUE THREAD

**Issue by lyhistory** [quickfix-j/quickfixj#248]
**feature request**
for high currency scenario, it always require to upsize applications default backlog

**proposed solution**
add config support, for example in acceptor.cfg

**Additional context**
I have checked on my server, the default backlog is 50

**Comment by chrjohn** [comment]
Sorry, which backlog are you referring to? Do you mean the watermarks for the queues?

**Comment by lyhistory** [comment]
I mean tcp backlog, org.apache.mina.transport.socket.nio.NioSocketAcceptor.setBacklog(backlogsize), not sure is there an easy way to increase the size for the tcp connection, I think default value is 50

**Comment by chrjohn** [comment]
OK, the TCP backlog. As far as I understand the backlog is for pending (not established) incoming connections. Do you have more than 50 connections build up at roughly the same time?

**Comment by lyhistory** [comment]
after I talked with my colleagues, I was told that have that much connections for now, actually I just joined this financial industry, I was looking at it purely from technical viewpoints, maybe for real cases 50 is good enough, you may close this ticket in this case, thanks for you quick reply.
