### ISSUE TITLE
How to handle NewOrderList in an ExecutionReport

### ISSUE THREAD

**Issue by sandeepsuvit** [quickfix-j/quickfixj#251]
Hi i am new to fix protocols, i was wondering how to process a NewOrderList from an ExecutionReport. As per a fix message document on the internet ```https://gainfutures.com/api/html/133e2886-5411-44b7-b781-2311a45ab540.htm``` i came to know that every order in the NewOrderList will be processed one at a time in the ExecutionReport.

From the above doc:
```order statuses and trades are reported for individual orders, not for the list as whole```. 

Is there a way i can get the list of order details back from the ExecutionReport event listener using below

```java
public void onMessage(ExecutionReport report, SessionID sessionID) {
        // handler implementation
}
```

**Comment by chrjohn** [comment]
This is the issue tracker and no support forum. Please use the mailing list:  https://sourceforge.net/projects/quickfixj/lists/quickfixj-users
Thanks.
