### ISSUE TITLE
Security Contact Requested

### ISSUE THREAD

**Issue by prodigysml** [quickfix-j/quickfixj#252]
@n33dle and I found a security vulnerability within the quickfixj project. We were hoping to get a core maintainer's contact details to responsibly disclose this vulnerability.

**Comment by chrjohn** [comment]
Is it a vulnerability in quickfixj or a used library? However you can contact me on christoph.john-at-macd.com
Thanks in advance

**Comment by chrjohn** [comment]
Hi @prodigysml , @n33dle
Did not receive an email yet. Are you maybe referring to this: https://github.com/quickfix-j/quickfixj/pull/239 (Bump dom4j from 2.1.0 to 2.1.1 in /quickfixj-dictgenerator)

**Comment by chrjohn** [comment]
#239 has been merged now.

**Comment by prodigysml** [comment]
Apologies for the delay. Yup I believe that was the vulnerability.

**Comment by prodigysml** [comment]
Just as an FYI, there is also this location:
https://github.com/quickfix-j/quickfixj/blob/master/quickfixj-core/src/main/java/quickfix/DataDictionary.java#L870-L874
