### ISSUE TITLE
Add TLS SNI support

### ISSUE THREAD

**Issue by youurayy** [quickfix-j/quickfixj#276]
**Is your feature request related to a problem? Please describe.**
Quickfix/J now supports SSL, which is great, but to fully leverage this when running a mutli-client server in a managed (Kuberenetes/Traefik2) environment (and many others), one can't always allocate a new port for each new session, and instread 3rd+ level hostnames are used to distinguish. For this to work, a SNI header should be added to the initiator connection (JDK fully supports this since version 7 I think).
https://en.wikipedia.org/wiki/Server_Name_Indication

**Describe the solution you'd like**
A SNI header should be added to the initiator connection (JDK fully supports this since version 7 I think).

**Describe alternatives you've considered**
Alternative is to use something like stunnel, or allocate ports per connection, neither of which is nice, given that we have the differentiating mechanism already available.

**Additional context**
SNI shoul be enabled by default when using TLS -- servers which don't support it simply ignore it.

**Comment by youurayy** [comment]
As for implementation tip, I've found this: https://stackoverflow.com/questions/20432233/apache-mina-sni-implementation

**Comment by chrjohn** [comment]
Thanks for the tip, sounds pretty straight forward and sensible. 

Did I mention that we welcome pull requests? ;)
At the moment I'm struggling to tick off my to do list...

**Comment by the-thing** [comment]
I will have a look at this, but no promises.

**Comment by chrjohn** [comment]
Thanks Marcin. :+1: Just let us know when you don't find the time.

Cheers,
Chris.

**Comment by youurayy** [comment]
Thanks guys! Yeah let me know if work is needed.

**Comment by the-thing** [comment]
I don't have a deep understanding of SNI, but I did some reading and I was able to prototype the change and I can see that the extension is populated in ClientHello message. The information you provided was correct.

Handshake log
`Extension server_name, server_name: [type=host_name (0), value=kubernetes.docker.internal]`

My etc/hosts entry

`127.0.0.1 kubernetes.docker.internal`

There are some issues that I encountered and you might be able to help. I read in  https://tools.ietf.org/html/rfc6066#section-3

> A server that receives a client hello containing the "server_name"
> extension MAY use the information contained in the extension to guide
> its selection of an appropriate certificate to return to the client,
> and/or other aspects of security policy.  In this event, the server
> SHALL include an extension of type "server_name" in the (extended)
> server hello.  The "extension_data" field of this extension SHALL be
> empty.
> 

As far as I can see this is not supported in Java in current key manager implementation. When server chooses which certificate to send to the client it chooses "randomly" (usually first certificate inside the keystore)

`sun.security.ssl.SunX509KeyManagerImpl#chooseServerAlias`

Imagine a following scenario. Server keystore contains 3 key-pairs with aliases "a", "b", "c" and client truststore contains single trusted certificate - "b". Client will fail server authentication as it will most likely recieve "a" and providing SNI will not help much. To support this custom key manager must be implemented.

So the following questions are.

1) Is there much value providing SNI for initiators without implementing custom key manager that appropriate certificate would be returned? (I assume provided SNI would have to match CN of the certificate or maybe even certificate SAN extensions - I don't really know as these are separate extensions)

2) Do we want to add acceptor server name validation via `javax.net.ssl.SNIMatcher`? (probably we would to have to add new config to FIX settings to provide a list of hosts that are supported or take them from available certificates in the server keystore)

**Comment by youurayy** [comment]
Hi Marcin (@the-thing) -- before seeing your last message -- I have created and tested a PR which enables the SNI. I see you mention you already have done the same work, sorry about that.

Regarding multiple certificates, we use a wildcard SSL certificate, which I think is common in a multiple virtual-hosts scenario.

So 1., for us this definitely makes sense as is, and 2. this would cover multiple-certs scenario, but perhaps this could be added once people actually request it?

**Comment by the-thing** [comment]
If this brings value I guess this might make sense without either 1 or 2. I was expecting that 1 would be actual requirement by the RFC, but it is not.

**Comment by the-thing** [comment]
There are a few things that I would add to this pull request (not related to stuff that we already discussed)

1) Add new SSL initiator session settings parameter "EndpointIdentificationAlgorithm" (with no default value), which would be provided in `javax.net.ssl.SSLParameters#setEndpointIdentificationAlgorithm`. If provided, this would trigger client side identity check (seems like wildcards are supported out of box). **The problem - I don't see mina supporting this.**

2) This would allow to write more end to end tests cases in `quickfix.mina.ssl.SSLCertificateTest` e.g.
	
	- scenario where SNI does not match certificate CN (no QuickFIX session created)
	- scenario where SNI matches exactly certificate CN
	- scenario where SNI matches wildcard certificate CN
	
3) Update QuickFIX SSL documentation page with new parameter description. (seems like HTTPS, LDAP, LDAPS values are supported, but I think only HTTPS is relevant).

**Comment by youurayy** [comment]
@the-thing yes, unfortunately the `javax.net.ssl.SSLContext.createSSLEngine()` methods are `final`, so we can't subclass `SSLContext` to perform the `setEndpointIdentificationAlgorithm()` call on the newly created engine. Likewise the `SSLContextSpi` class is a private Sun implementation.
Then Mina guards this in `SslHandler.init()`, so that is the place we would have to submit a PR to Mina to add support for this.

Given the above, and given that the SNI support is now opt-in, what would you see as the next course of action? I'm assuming, given the above, it makes no sense to write SNI-specific tests.

**Comment by the-thing** [comment]
Endpoint identification algorithm is not supported so can't be done at the moment. SNI server matcher and server keystore picking appropriate certificate maybe can be done in the future if there is a need for it.

If the current PR brings value, possibly could be merged.

**Comment by youurayy** [comment]
@the-thing great, thanks. For us, it would allow us to get rid of VPN (IpSec, libreswan) which is a pain to setup, maintain and some partners have trouble reconnecting with it. TLS/SNI will solve this.

I just need to unblock the PR due to the LGTM config, not sure if I can commit that LGTM yaml config file to do so, would be great if someone could review my latest comment on the PR.

**Comment by chrjohn** [comment]
Sorry, a little busy at the moment. Will comment on the PR.

**Comment by youurayy** [comment]
@chrjohn I wasn't able to fix the LGTM integration from within the PR, as it's something that need to be fixed on a higher level (I've left a comment on the PR).

So I'll leave it here, and pls let me know if there's anything more I should do to get this PR merged.

Thanks!
