### ISSUE TITLE
ThreadedSocketInitiator reloads all sessions if one session fails

### ISSUE THREAD

**Issue by mrFloony** [quickfix-j/quickfixj#294]
Starting with version 2.1.1, I started using the ThreadedSocketInitiator. And there is a problem when, in the event of a failure in one session (for example, the message does not pass the time correctness check - **Session.isGoodTime** method), all sessions reboot, which takes several seconds. Is it possible to handle reloading only an erroneous session, leaving the remaining sessions in operation?

**Comment by chrjohn** [comment]
This sounds strange. However, could you please use the mailing list for general help requests? Best would be if you provided some logs of the problematic behaviour. Thanks in advance.
