### ISSUE TITLE
Connecting over an authenticating HTTP proxy fails

### ISSUE THREAD

**Issue by curdreinert** [quickfix-j/quickfixj#295]
We are trying to connect over an HTTP proxy that enforces authentication, i.e. user and password need to be set. But even though we put them into the dictionary (and set the appropriate proxy type and the correct proxy host and port) the connection fails.

Snooping into the network traffic with wireshark reveals that, at first, a CONNECT request is sent by our application to the proxy. As usual, this initial request contains no authentication data, and is answered by the proxy with an 407 Authentication Required. The expected behaviour would be that a new CONNECT request is send, this time with a Basic Proxy-Authorization header containing the user and password. Instead, the connection is closed.

I ran the code in a debugger and found that the problem seems to be that in quickfix.mina.ProtocolFactory (line 145 to 150) a prefered order of the authentication methods is set into the proxyIoSession. This order, however, has NO_AUTH at the first position. So that, after receiving the 407 and when going through the possible authentication methods, Mina's HttpSmartProxyHandler first encounters a NO_AUTH and sees this as a sign that every further search for an authentication method is futile. And therefore closes the connection.

The prefered order of the authentication methods in ProtocolFactory seems to be rather obviously wrong. But instead of correcting it, you might want to just _not_ set it, in which case Mina would go with their own idea of which method to prefer, which seems to be a good idea.

I forced the prefered order list to be null in my debugger, and was able to succesfully connect through the proxy.

**Comment by curdreinert** [comment]
I just noticed that at the end of the discussion of https://github.com/quickfix-j/quickfixj/pull/92 the same issue with pretty much the same explanation was mentioned. I can confirm that the current prefered order prevents the authentication with http proxies from working, and that setting no order at all would be better.

**Comment by chrjohn** [comment]
Sounds like a simple fix to me. Maybe someone with more proxy experience than me can comment whether this change will break something else.
Maybe we should make it configurable?

**Comment by chrjohn** [comment]
Will removing the prefered order also work with a proxy without username and password?

**Comment by curdreinert** [comment]
The whole method autoSelectAuthHandler in HttpSmartProxyHandler.java is only ever reached after the 407, i.e. only if the proxy needs authentication.
So yes, removing the prefered order also works with a proxy without username and password.

**Comment by the-thing** [comment]
Are you guys working on it or planning to or can I pick it up?

**Comment by chrjohn** [comment]
@the-thing , feel free to do it. Thanks in advance. :)

**Comment by the-thing** [comment]
It should be, but I will set up a proxy on myst host as I need some test evidence to confirm.

**Comment by curdreinert** [comment]
I could do some testing with the proxy I've set up to analyze this.
