### ISSUE TITLE
Certain JMX beans' attributes  are broken due to a bug in CompositeTypeFactory

### ISSUE THREAD

**Issue by the-thing** [quickfix-j/quickfixj#304]
**Describe the bug**
Certain attributes are unavailable via JMX.

**To Reproduce**
Connect via JMX and check the attributes.

**Expected behavior**
Composite values should be visible via JMX.

**Additional context**
`org.quickfixj.jmx.openmbean.CompositeTypeFactory` allows to add items without description via `#defineItem(java.lang.String, javax.management.openmbean.OpenType)` - which is actually being used . However, https://github.com/quickfix-j/quickfixj/pull/205 PR has mistaken actual functionality for a typo.

Currently broken items seem to be:
- AcceptorAddresses
- Endpoints
- Sessions/Session
- Sessions/SessionID

I will be producing fix soon.

![image](https://user-images.githubusercontent.com/3160158/86045909-32bcd500-ba44-11ea-82c3-0dcb59990688.png)

**Comment by the-thing** [comment]
I produced a patch locally, but while gathering test evidence it seems that JMX MBean "org.quickfix -> Initiator -> Attributes -> Endpoints" is still broken.

For acceptor we have two indexed composite types "AcceptorAddresses" and "Sessions". For initiator we have also two "Endpoints" and "Sessions".

It seems that JMX "Endpoints" were broken by 7f670abbfbe554c1f0230863765dc8f5d06af7e5 by removing properties, but I'm not entirely sure.

Do we know what is supposed to be displayed under "Endpoints"? Are the contents supposed to be the same as for AcceptorAddresses (AcceptorAddresses, SessionID, SessionName) with exception to InitiatorAddresses?

**Comment by chrjohn** [comment]
@the-thing , to be honest I don't know what the "Endpoints" page should show. We are using JMX programmatically for monitoring our FIX sessions and it works. :-/ But your assumption about the InitiatorAddresses makes sense.

**Comment by the-thing** [comment]
Have you tested the new version? Clearly `javax.management.openmbean.CompositeType#CompositeType` that is called by https://github.com/quickfix-j/quickfixj/blob/23aa52c88ff48850ae20ecd281bce2dc9442b1a2/quickfixj-core/src/main/java/org/quickfixj/jmx/openmbean/CompositeTypeFactory.java#L55  will throw exception when any of description elements is null. Arguments are validated in the constructor.

It would be good great if you could share how do you you connect to JMX, but the JConsole client is broken.
