### ISSUE TITLE
QFJ upgrade issue from 2.1.1 to 2.2.0 due to XMLConstants.ACCESS_EXTERNAL_DTD

### ISSUE THREAD

**Issue by jatin107** [quickfix-j/quickfixj#306]
**Describe the bug**
I am trying to upgrade the QFJ version 2.2.0 from 2.1.1 facing below issue.

java.lang.IllegalArgumentException: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.
    at org.apache.xerces.jaxp.DocumentBuilderFactoryImpl.setAttribute(Unknown Source)
I have analysed this is because of QFJ DataDictionary.java's load method using below code.

 private void load(InputStream inputStream) throws ConfigError {
final DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
factory.setAttribute(XMLConstants.ACCESS_EXTERNAL_DTD, "");
factory.setAttribute(XMLConstants.ACCESS_EXTERNAL_SCHEMA, "");
...}
Reason of error is not clearly understood by me(please try to explain) but found that Xerces, xercesImpl jar causing this error.

we are using these jar in some our project code that is why it is needed.

Can anyone try to explain why we have placed these lines? and we are placing then it should be under try and catch block. Is there any way to fix it. Without doing source code changes provide by QFJ. Answer from QFJ team really appreciated.

**To Reproduce**
Just add Xerces, xercesImpl jar in class path.
**Expected behaviour**
Does not throw a runtime exception. A normal warning log message is fine.

**system information:**
 - OS: [e.g. Windpw]
 - Java version [e.g. JDK8]
 - QFJ Version [e.g. 2.2.0]

**Comment by the-thing** [comment]
The change was made as part of https://github.com/quickfix-j/quickfixj/issues/299

Which version of Xerces are you using? Have a look at https://www.quickfixj.org/usermanual/2.1.0/installation.html

> By default, the XML processing in QuickFIX/J uses the XML parser included with the JDK. In general other parsers can be used but it's possible you will have problems. We've had users report that Xerces 2.6 does not work, but that version 2.8 does. If you try other parsers, please let us know if it works or not.

**Comment by jatin107** [comment]
thanks for your extremely fast reply. I got the reason for the change as per #299 . I am using below jars version.
xerces-2.2.1
xercesImpl-2.8.1 (on 2.1.1 is it working fine)

I have gone through the line *We've had users report that Xerces 2.6 does not work, but that version 2.8 does*
it will great try to set the XMLConstants property file. 

One Question if we place setAttribute line try and catch block do we have other impact or any other change required by our side. I have run QFJ test cases is passed. but want confirmation from your side.

**Comment by the-thing** [comment]
> One Question if we place setAttribute lines try and catch block do we have other impact or any other change required by our side. I have run QFJ test cases is passed but want confirmation from your side.

Are you suggesting a fix in quickfixj or are you planning to rebuild the project locally? This would have to be tested with different version of Xerces.

I will have a look probably at some point this week why certain versions of Xerces do not work. I think enabling data dictionary to use custom DocumentBuilderFactory would be a reasonable way to solve it (via constructor or setter etc.).

**Comment by jatin107** [comment]
> Are you suggesting a fix in a quick fix or are you planning to rebuild the project locally? This would have to be tested with a different version of Xerces.

As of own, locally, it will great if do the same in QFJ or provide some better solution.
I have tested with the latest version also like xercesImpl2.12.0, Xerces:2.4.0

Again thanks for your reply.

**Comment by the-thing** [comment]
At the end it seems that only a single version of xerces works with these properties. 

```
<project>
  <groupId>xerces</groupId>
  <artifactId>xerces</artifactId>
  <version>1.2.3</version>
</project>
```

None of other versions of` xerces:xerces` or `xerces:xercesImpl` available in Maven Central do work.

**Comment by chrjohn** [comment]
Hmm, there is https://issues.apache.org/jira/browse/XERCESJ-1654 which is about 5 years old but not implemented yet.

**Comment by the-thing** [comment]
Good find. That explains a lot. I don't think we can expect it anytime soon.

**Comment by chrjohn** [comment]
Sorry for provoking this. I thought every recent XML parser should be able to interpret these constants. :-/

**Comment by the-thing** [comment]
This would be a reasonable assumption right? These things are supported, but the names seem to be different than those defined in `javax.xml.XMLConstants`

Example.

https://xerces.apache.org/xerces2-j/features.html e.g. http://apache.org/xml/features/nonvalidating/load-external-dtd

https://xerces.apache.org/xerces2-j/properties.html e.g. http://apache.org/xml/properties/schema/external-schemaLocation

**Comment by simenflatby** [comment]
Hi @chrjohn @the-thing. I have encountered the same problem after upgrading from `2.1.1` to `2.2.0`.

My project originally had `xercesImpl-2.9.0.jar` on the classpath. With `xercesImpl-2.9.0.jar`, the initiator would not start.
```
{lines removed}
Caused by: quickfix.ConfigError: FIXT11-{custom name removed}.xml: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.
        at quickfix.DataDictionary.read(DataDictionary.java:871)
        at quickfix.DataDictionary.<init>(DataDictionary.java:104)
        at quickfix.DefaultSessionFactory.lambda$static$0(DefaultSessionFactory.java:42)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
        at org.quickfixj.SimpleCache.computeIfAbsent(SimpleCache.java:41)
        at quickfix.DefaultSessionFactory.getDataDictionary(DefaultSessionFactory.java:366)
        at quickfix.DefaultSessionFactory.createDataDictionary(DefaultSessionFactory.java:269)
        at quickfix.DefaultSessionFactory.processFixtDataDictionaries(DefaultSessionFactory.java:304)
        at quickfix.DefaultSessionFactory.create(DefaultSessionFactory.java:152)
        at quickfix.mina.SessionConnector.createSession(SessionConnector.java:182)
        at quickfix.mina.initiator.AbstractSocketInitiator.createSessions(AbstractSocketInitiator.java:214)
        at quickfix.mina.initiator.AbstractSocketInitiator.createSessionInitiators(AbstractSocketInitiator.java:105)
        at quickfix.ThreadedSocketInitiator.start(ThreadedSocketInitiator.java:105)
        {line removed}
        ... 4 more
Caused by: java.lang.IllegalArgumentException: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.
        at org.apache.xerces.jaxp.DocumentBuilderFactoryImpl.setAttribute(Unknown Source)
        at quickfix.DataDictionary.load(DataDictionary.java:883)
        at quickfix.DataDictionary.read(DataDictionary.java:869)
        ... 17 more
```

After replacing `xercesImpl-2.9.0.jar` with `xerces-1.2.3.jar` as suggested in https://github.com/quickfix-j/quickfixj/issues/306#issuecomment-656077105, the initiator starts, but I encounter a similar exception when transforming messages to XML:
```
{lines removed}
java.lang.RuntimeException: java.lang.IllegalArgumentException: Not supported: http://javax.xml.XMLConstants/property/accessExternalDTD
        at quickfix.Message.toXML(Message.java:355)
        {lines removed}
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        {lines removed}
        at quickfix.Session.sendRaw(Session.java:2598)
        at quickfix.Session.generateHeartbeat(Session.java:1997)
        at quickfix.Session.next(Session.java:1970)
        at quickfix.Session.next(Session.java:1188)
        at quickfix.Session.next(Session.java:1227)
        at quickfix.mina.ThreadPerSessionEventHandlingStrategy$MessageDispatchingThread.doRun(ThreadPerSessionEventHandlingStrategy.java:222)
        at quickfix.mina.ThreadPerSessionEventHandlingStrategy$ThreadAdapter.run(ThreadPerSessionEventHandlingStrategy.java:146)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Not supported: http://javax.xml.XMLConstants/property/accessExternalDTD
        at org.apache.xalan.processor.TransformerFactoryImpl.setAttribute(TransformerFactoryImpl.java:576)
        at quickfix.Message.toXML(Message.java:347)
        ... 23 more
```

Do you have a timeframe scheduled for when to release `2.2.1` with #307? Downgrading to `2.1.1` is not an option because I need #264.

**Comment by chrjohn** [comment]
Hi @simenflatby ,
sorry, no defined date for 2.2.1 yet. But I'll also have one issue or two that I'd like to get fixed. Cannot promise anything at the moment but I'll try to work on this next week or the week after.

**Comment by simenflatby** [comment]
Confirm that #307 works with `xercesImpl-2.9.0.jar`.

**Comment by mrFloony** [comment]
Hi, guys
User _Abhishek Singh_ found a solution to a similar problem (with a library **xercesImpl**): https://stackoverflow.com/questions/58374278/org-xml-sax-saxnotrecognizedexception-property-http-javax-xml-xmlconstants-p

In a nutshell: you need to disable the use of the **xercesImpl** internal library in the application server (for example, wildfly). 

This solution does not affect the library **quickfix**, but only used application server.
Current solution is temporary, but allows running version 2.2.0.

**Comment by simenflatby** [comment]
@mrFloony Thank you for the heads up. This does not work for my use case though. Not running QuickFIX/J in an app server.

**Comment by FlyingSheepOnSailfish** [comment]
We also had the same error on upgrading to QFJ 2.2.0

On close inspection this is a case of "XML Parser Hell" raising its ugly head again.

The root problem is that a java application with multiple 3rd Party jars can have multiple competing XML Parsers, and even multiple implementations of Xerces on the classpath.

To the uninitiated it seems complete voodoo as to which XML parser is used where.

Upgrade the JRE, or a third party lib, make a small change to the classpath, and suddenly XML parsing will cause errors, or work slightly differently because a different XML Parser is now being used.

In the past we have struggled with these XML Parsers:
* Xerces from org.apache
* Xerces from the JRE
* Xerces from org.apache via Eclipse BIRT
* Oracle XMLParserv2
* org.apache.crimson from the Crimson jar

Many years ago we hit on the solution to tie down the XML Parser to something predictable by adding the line below at the very start of our application.

`System.setProperty("javax.xml.parsers.DocumentBuilderFactory", "org.apache.xerces.jaxp.DocumentBuilderFactoryImpl");`

This used an apache Xerces 2.9 implementation (via Eclispe BIRT), but with QFJ 2.2.0 gave the "Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized." error.

If we change to the Xerces 2.12.0. implementation provided by the JRE Zulu_8_u272:

`System.setProperty("javax.xml.parsers.DocumentBuilderFactory", "com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl");`

..then QFJ 2.2.0 starts without error.

**Comment by chrjohn** [comment]
Hi @FlyingSheepOnSailfish , thanks for the detailed instructions. :+1:

**Comment by FlyingSheepOnSailfish** [comment]
@chrjohn, am pleased to help: We take the same approach for TransformerFactoryImpl, DocumentFactoryImpl and SAXParserFactoryImpl. i.e. we button all three down to known implementations with:
```
      if(System.getProperty("javax.xml.transform.TransformerFactory")==null) {
        System.setProperty("javax.xml.transform.TransformerFactory", "com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl");
      }
      if(System.getProperty("javax.xml.parsers.DocumentBuilderFactory")==null) {
        System.setProperty("javax.xml.parsers.DocumentBuilderFactory", "com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl");
      }  
      if(System.getProperty("javax.xml.parsers.SAXParserFactory")==null) {
         System.setProperty("javax.xml.parsers.SAXParserFactory", "com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl");
      }
```
