### ISSUE TITLE
ResetOnLogon/ResetOnLogout/ResetOnDisconnect fails when PersistMessages is set to 'N'

### ISSUE THREAD

**Issue by dparui** [quickfix-j/quickfixj#314]
**Describe the bug**
ResetOnLogon/ResetOnLogout/ResetOnDisconnect fails when PersistMessages is set to 'N'. It throws an IOException "Invalid object name `messages`"

at quickfix.JdbcStore.reset(JdbcStore.java:195)

**To Reproduce**
Set `ResetOnLogon/ResetOnLogout/ResetOnDisconnect` to `Y` and `PersistMessages` to `N`. When Logon/Logout/Disconnect event occurs, the session tries to reset state, which in turn tries to reset the message store. On JdbcStore, this results in trying to delete from `messages` table, before updating the `sessions` table. If `PersistMessages` is set to `N`, no `messages` table is created.

**Expected behavior**
If `PersistMessages` is set to `N`, no attempt should be made to delete from `messages` table.

**system information:**
 - OS: Linux
 - Java version JDK8
 - QFJ Version 2.2.0

**Additional context**
Either update https://www.quickfixj.org/usermanual/2.1.0/usage/configuration.html to clearly mention which settings can be used in conjunction with another. Or pull delete messages logic from lines 182-185 in `JdbcStore.java` (QFJ Version 2.2.0) into a separate method `deleteMessages` and call it from line 2661 of `Session.java` with a check if `persistMessages` is `true` around it.

**Comment by chrjohn** [comment]
Good catch, thanks. Are you able to provide a PR with the check for `persistMessages`?

**Comment by dparui** [comment]
@chrjohn Sure I can.

**Comment by chrjohn** [comment]
No. 


>@chrjohn Do you follow a particular pattern for branch names for bugs?

**Comment by dparui** [comment]
PR raised. https://github.com/quickfix-j/quickfixj/pull/316

**Comment by chrjohn** [comment]
Hi @dparui ,
sorry for the long delay. Slowly working through the open PRs... I have a question regarding this issue. You state that:

> If PersistMessages is set to N, no messages table is created.

Do you mean that *you* do not create the messages table? I think the sql scripts will create all the tables regardless of any properties like `PersistMessages`.

Thanks,
Chris.

**Comment by dparui** [comment]
Hi,

No worries.

Messages table is neither created manually nor automatically. If the requirement is to not to persist messages, why create `messages` table at all. Also more importantly, why attempt deleting from `messages` table if `PersistMessages` is set to `N`. 

Thanks,
Chris.

**Comment by chrjohn** [comment]
OK, let's do the rest of the discussion on the PR #316
