### ISSUE TITLE
Support for FIX Latest

### ISSUE THREAD

**Issue by david-gibbs-ig** [quickfix-j/quickfixj#317]
It  would be good for QFJ to support FIX Latest from FTC. If this is done by means of a dependency on the published FIX Latest Repository (Orchestration).

I would suggest that FIXLatest be added as an additional module to preserve backward compatibility of the existing FIX50sp2 module.

This would also provide a ready means for users to depend on their customized repositories instead of the base-line FIX Standard.

The FIX Latest repo includes some extension packs that break the QFJ build so code generated for messages in the new FIX50sp2Latest needs to be slightly different. The problem is where components and fields have the same name. As Java does not overload based on return type the method name for components must change. For backward compatibility this should not be applied to messages for prior versions of the standard.

I will provide an example build. See the branch here : https://github.com/david-gibbs-ig/quickfixj/tree/fix-orchestra
This above is a work in progress,

**Comment by david-gibbs-ig** [comment]
To see how this might work, you can check this branch https://github.com/david-gibbs-ig/quickfixj/tree/fix-orchestra. I have added some readmes in an attempt to explain the changes. I can't get it to build on Travis as the "travis_wait" directive does not seem to have any effect and the build times out.

**Comment by david-gibbs-ig** [comment]
This link provided for context : https://www.fixtrading.org/fix-online-specification-updated-to-fix-latest/

**Comment by david-gibbs-ig** [comment]
Hi the build for the branch https://github.com/david-gibbs-ig/quickfixj/tree/fix-orchestra works for Java 8, it just will never work in Travis because it takes 1.5 hours.  Are you in the process of migrating to git actions ?

**Comment by JThoennes** [comment]
@chrjohn Do you have any plans to release this? Cheers, Jörg

**Comment by chrjohn** [comment]
Not in the next version, will be 3.0.0 most probably.

**Comment by JThoennes** [comment]
@chrjohn 
> Not in the next version, will be 3.0.0 most probably.
Do you have any concrete plans for version 3? What it will contain and when you expect it to arrive?

**Comment by chrjohn** [comment]
No concrete plans at the moment. Currently trying to get 2.2.1 (as I think about it, it should probably be called 2.3.0) out of the door.

What 3.0.0 will contain: up to now this: https://github.com/quickfix-j/quickfixj/milestone/10
It is loosely planned that 3.0.0 will also contain support for FIX Orchestra as far as validation is concerned, i.e. directly validate against an Orchestra file.

**Comment by chrjohn** [comment]
Hi @david-gibbs-ig , I want to take a look at this in the near future. What do you think about building the FIXLatest classes and dictionary in an external module outside of QFJ and pull it in as a dependency? I think we realized here https://github.com/quickfix-j/quickfixj/pull/333 that the build with the QFJ code generator is too slow. 
Thanks,
Chirs.

**Comment by david-gibbs-ig** [comment]
Hi Christophe,

Apologies I have been working flat out for weeks, I think that the way ahead may be to use the FTC code generation which is faster.
We can start with doing this for FIX latest only to make sure it is OK. I got part way there but was blocked by a problem, I will revisit this and reply to you soon.

DAVID GIBBS
Technology Architect

IG, Cannon Bridge House 25 Dowgate Hill, London, EC4R 2YA
D: +442075730697 | T: +442078960011
www.ig.com

45 YEARS OF TRADING
INDICES | SHARES | FOREX
COMMODITIES

**Comment by david-gibbs-ig** [comment]
Please see https://github.com/quickfix-j/quickfixj/pull/457.
