### ISSUE TITLE
Do not log cleartext password on logon failure

### ISSUE THREAD

**Issue by fillreject** [quickfix-j/quickfixj#330]
**Describe the bug**
Full FIX message with cleartext password is logged on logon failure.

**Expected behavior**
Either do not log the FIX message, or remove cleartext password from the message.

**Comment by philipwhiuk** [comment]
How widely are plain-text passwords actually used for authentication vs certificates. This feels like fixing a rare problem in the wrong place. In my experience connections are established over SSL-auth'd tunnels.

1. If you don't want to log the password in plain text, hash the password
2. That's still vulnerable to replay of course, so you could use something like SCRAM.
3. For everyone else, bad logons are rare and thus useful information. This should be opt-in.

You also might consider contributing to https://www.fixtrading.org/groups/cyberfixa/

**Comment by chrjohn** [comment]
Thanks @philipwhiuk  for your comments. Making this configurable seems to be the way to go then.

So `settings` or the to-be-created setting for this need to be handed through to the `AcceptorIoHandler`.

**Comment by fillreject** [comment]
It does look like messageString is useful for debugging. Would it be acceptable to include it in _debug_ log only? Error log will contain remoteSessionID instead, as proposed by @lyncmi07.

That also does not require a new setting to be created.

**Comment by chrjohn** [comment]
I don't know how the others see this but I do not have DEBUG logging enabled on PROD.

**Comment by fillreject** [comment]
Thanks @chrjohn, I created another PR (https://github.com/quickfix-j/quickfixj/pull/340). This leaves messageString logging as it is, but allows to disable verbose logging.
