### ISSUE TITLE
Relying on ancient version of Berkeley DB JE

### ISSUE THREAD

**Issue by hyandell** [quickfix-j/quickfixj#334]
Hi Quickfix folk,

I just wanted to note that the https://github.com/quickfix-j/quickfixj/blob/master/quickfixj-core/pom.xml file is depending on a 2006 version of Berkeley DB JE, with strong copyleft licensing. 

That project was relicensed to Apache-2.0 a few years ago, and presumably has bugfixes/security fixes that would be useful for Quickfix users.

Might I recommend that you update the dependency?

**Comment by chrjohn** [comment]
Thanks for the pointer. We welcome pull requests. :)

**Comment by chrjohn** [comment]
OK, think I found the right dependency now.
