### ISSUE TITLE
Allow custom DataDictionaryProvider in DefaultSessionFactory

### ISSUE THREAD

**Issue by cebaa** [quickfix-j/quickfixj#339]
**Is your feature request related to a problem? Please describe.**
Right now, the dictionary has to be read from the file. Specifically, it cannot be read from the classpath (i.e. embedded within a jar).

**Describe the solution you'd like**
Add another constructor to `DefaultSessionFactory` which accepts a custom `DataDictionaryProvider` to be used in `create` instead of `DefaultDataDictionaryProvider`.

**Describe alternatives you've considered**
Alternatives would be adding a `Supplier` or something along those lines.

**Additional context**
N/A

**Comment by chrjohn** [comment]
Hmm, not true actually. You can read dictionary from file, url or classpath.

https://github.com/quickfix-j/quickfixj/blob/fc152637822382be2666a28dcb8956fe7dd1d6fc/quickfixj-core/src/main/java/quickfix/DataDictionary.java#L903-L905
Or did I miss something in your issue?

**Comment by chrjohn** [comment]
We are using reading from within JAR in many places in our applications.

**Comment by cebaa** [comment]
@chrjohn You can read the dictionary itself, but when using `SocketInitiator` with  `Session.SETTING_USE_DATA_DICTIONARY == "Y"`, it will use the dictionary that `DefaultSessionFactory` gets via `DataDictionaryProvider` which is hard-coded to `DefaultDataDictionaryProvider`: https://github.com/quickfix-j/quickfixj/blob/b1eb16b89192805e300073d26e85e0efccce62b1/quickfixj-core/src/main/java/quickfix/DefaultSessionFactory.java#L142-L156

Am I right that there's no way to initialize `SocketInitiator` with a custom dictionary that is read from a jar file?

**Comment by chrjohn** [comment]
Did you step through the source code? The provider eventually goes through the load method I mentioned earlier. 

I assume you have specified the property wrong maybe? Can you post that part of the config and the path of the dictionary in your JAR?

Am 27. November 2020 16:26:47 MEZ schrieb cebaa <notifications@github.com>:

**Comment by chrjohn** [comment]
Please reopen if you feel this is still relevant.
