### ISSUE TITLE
SessionStateListener not notified about initial connection failures

### ISSUE THREAD

**Issue by drekbour** [quickfix-j/quickfixj#342]
**Describe the bug**
If a Session wholly fails to initialise (never gets as far as a TCP connection) nothing is notified to its SessionStateListener

**To Reproduce**
* Add a SessionStateListener to to a Session configured such that it will never connect
* Observe the event log has something like 'java.net.ConnectException during connection to /localhost:80: java.net.ConnectException: Connection timed out (Next retry in 30000 milliseconds)'

**Expected behavior**
Something to be notified to your listener (`onDisconnect` ?)

**system information:**
 - QFJ 2.1.1

**Additional context**
The exception shown above is sent to the qfj `Log` framework then swallowed by `quickfix.mina.initiator.IoSessionInitiator.ConnectTask#handleConnectException`

Listener `onDisconnect` is the only viable existing method that would be suitable although I don't know if it's necessarily the right choice. That rather depends on how it used for other categories of first-time initialisation error (i.e. an SSL error or FW issue) that manifest _after_ TCP is connected.

**Comment by chrjohn** [comment]
Hi @drekbour , I was thinking about adding an `onConnectException()` method to the `SessionStateListener`. I just wanted to know how you add the listener to your `Session`.
Currently you either have the possibility to implement the `SessionStateListener` in your `Store` or `Log` implementation or you can add it via `Session.addStateListener()`. However, the latter is only possible after the `Session` has been constructed, meaning *after* an `Initiator` has already been started. So there is the possibility that you do not get notified of all events in the case that the Exception happens very fast. On the other hand, when the Exception is non-transient it will happen again, notifiying the listener.

**Comment by drekbour** [comment]
I like the idea of auto-adding `Application` but that's not a _solution_ to this problem (different feature really). Do be aware of the faint regression possibility that an existing class implementing both `Application` and `SessionStateListener` might find itself registered twice.

"Doesn't work if X happens very fast" is never going to be the right answer for an electronic trading protocol :) (even if this is a _bootstrap_ event). Sounds like things are started before the construction phase is complete but that, again, might be a different issue as it's feels more structural than the basic reporting of the Exception?

**Comment by chrjohn** [comment]
You might have a point about the double registration when already existing applications implement `SessionStateListener`.
The solution to this problem would be to add a new method which gets notified of the Exceptions that are thrown when there are connection failures. The question is if this should be an all-new listener or an existing one.
So how do you add the listener to your Session?

About the "happens very fast": when an initiator is started it creates the associated `Sessions` in its `initialize()` method. So you wouldn't really have a chance to add the state listener until the startup of the initiator is complete. Preceding calls to `Session.lookupSession(foo)` might return `foo` as `null` then.

**Comment by drekbour** [comment]
In general terms, it sounds like Initiator shouldn't begin connecting before any pre-configured Sessions are created and notified. This is non-deterministic and anathema to debugging. My code call Session.addStateListener() inside `Application.onCreate()`. Auto-registering Application would be fine too - just make sure there's a release note to cover that double-registration possibility (or make ListenerSupport use CopyOnWriteArray*Set*!).

I think ... what I'm expecting is that `Application.onCreate(session)` happens-before (with all the semantics that implies) `SessionStateListener.onConnectException()` could occur.

If, on _not_ doing this, the worst case waiting 30s for another onConnectException - it's not the end of the world.

**Comment by chrjohn** [comment]
To be honest I rarely used the `SessionStateListener` and actually never thought of adding it in `Application.onCreate()`. This is the way to go. That way the behaviour I described in my first comment ("However, the latter is only possible after the Session has been constructed, meaning after an Initiator has already been started.") is not relevant anymore.

> Initiator shouldn't begin connecting before any pre-configured Sessions are created and notified
...
> what I'm expecting is that `Application.onCreate(session)` happens-before (with all the semantics that implies) `SessionStateListener.onConnectException()` could occur.

This will work as you describe. Initiator first creates the Sessions (which will call `Application.onCreate()`), registers them and then starts connecting (which could throw Exceptions).
https://github.com/quickfix-j/quickfixj/blob/dc3a5b712b1374ca484ade109d8ed07814e3e547/quickfixj-core/src/main/java/quickfix/mina/initiator/AbstractSocketInitiator.java#L204

**Comment by chrjohn** [comment]
Hi @drekbour I have created a PR, maybe you can check it out.
