### ISSUE TITLE
Obsolete reference to "ant" in the user manual.

### ISSUE THREAD

**Issue by david-gibbs-ig** [quickfix-j/quickfixj#343]
There is an obsolete reference to "ant" in the user manual.

See  https://www.quickfixj.org/usermanual/2.1.0/installation.html

and attached image

**Expected behavior**
Change "ant" to "mvn"

**system information:**
 - OS: [e.g. Linux]
 - Java version [e.g. JDK8]
 - QFJ Version [e.g. 2.1.0]+

**Additional context**

![image](https://user-images.githubusercontent.com/29655222/101807763-616bcb00-3b0d-11eb-8431-83f74a3352d4.png)

**Comment by felipewind** [comment]
I did this change locally, is it only this? Can I make a PR?

There are various command-line switches you can pass to **mvn** to modify the produced behavior:

![image](https://user-images.githubusercontent.com/47837222/106070655-a2329a00-60e3-11eb-9b56-24e4d972d623.png)

**Comment by chrjohn** [comment]
Looks OK to me @felipewind
