### ISSUE TITLE
QuickFIX/J uses unrecognized xerces property

### ISSUE THREAD

**Issue by davsclaus** [quickfix-j/quickfixj#346]
**Describe the bug**

Quickfix cannot load configuration file using XML parser from Xerces on runtimes where Xerces would throw an error configuring a property on the xml parser

**To Reproduce**
Steps to reproduce the behavior.
Or even better, a unit test or reproducer.

Reported at Apache Camel:
https://issues.apache.org/jira/browse/CAMEL-15281

**Expected behavior**

Quickfix should for the following code

        factory.setAttribute(XMLConstants.ACCESS_EXTERNAL_DTD, "");
        factory.setAttribute(XMLConstants.ACCESS_EXTERNAL_SCHEMA, "");

Use a try .. catch and maybe do a WARN log to indicate the attribute was not possible to configure

**system information:**
 - OS: [e.g. Linux]
 - Java version [e.g. JDK8]
 - QFJ Version [e.g. 2.1.1]

2.2.0

**Additional context**

**Comment by davsclaus** [comment]
It may be that on master this is _fixed_ as it seems that the code is changed and that these attributes are only set if the implementation is from com.sun.

**Comment by the-thing** [comment]
These properties only work with HotSpot `com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl` or older versions of Xerces.

This should have been fixed on master and released in QFJ 2.2.1. 

Issue https://github.com/quickfix-j/quickfixj/issues/306
PR https://github.com/quickfix-j/quickfixj/pull/307

Most likely Xerces dependency got updated in Camel (either directly or through transition) and/or class loading order has changed and different DocumentBuilder is used.

You should try using new version. In the new version you can also provide a custom `javax.xml.parsers.DocumentBuilderFactory` supplier in `quickfix.DataDictionary` if you need custom XML attributes.

**Comment by davsclaus** [comment]
Thanks for the feedback. We are then upgrading to 2.2.1 when it's released.

**Comment by chrjohn** [comment]
Thanks @the-thing for the quick resolution. :+1: 
Closing as duplicate.
