### ISSUE TITLE
Add Oracle DDL to messages_log and event_log

### ISSUE THREAD

**Issue by felipewind** [quickfix-j/quickfixj#348]
May I send a PR to add Oracle DDL of the `messages_log` and `event_log` tables?

I've tested locally using [Oracle 12c R2](https://hub.docker.com/_/oracle-database-enterprise-edition) with the `Banzai` example and everything worked fine.

![image](https://user-images.githubusercontent.com/47837222/103438137-6b658300-4c0e-11eb-8fb8-798f9c50785f.png)

![image](https://user-images.githubusercontent.com/47837222/103438144-83d59d80-4c0e-11eb-9057-d5bdca142560.png)

**Comment by chrjohn** [comment]
Hi @felipewind of course. :) please open a PR for this.
