### ISSUE TITLE
Correction in README toadmin

### ISSUE THREAD

**Issue by felipewind** [quickfix-j/quickfixj#350]
Can I send a PR making a small correction in `README.md` on the `toadmin` item?

If you think it's not worth the work I can close this issue, not a big deal!

### From
```
This allows you to add fields before an adminstrative message before it is sent out.
```

### To
```
This allows you to add fields to an administrative message before it is sent out.
```

**Comment by chrjohn** [comment]
Hi @felipewind , thanks, just send a PR :)
