### ISSUE TITLE
TimestampPrecision config can not work

### ISSUE THREAD

**Issue by minikiller** [quickfix-j/quickfixj#353]
**Describe the bug**
I found default TimestampPrecision is set to 3,but when i change it to 6, it can not work.

**To Reproduce**
[DEFAULT]
TimestampPrecision=6

**Expected behavior**
 52=20210110-01:57:10.176 can change to 52=20210110-01:57:10.176123

**system information:**
 - OS: macos
 - Java version JDK11
 - QFJ Version [2.2.0]

**Additional context**
none

**Comment by chrjohn** [comment]
Please check the valid values for that setting here: https://rawgit.com/quickfix-j/quickfixj/master/quickfixj-core/src/main/doc/usermanual/usage/configuration.html
`6` is not a valid value
