### ISSUE TITLE
Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.

### ISSUE THREAD

**Issue by cristipop93** [quickfix-j/quickfixj#354]
**Describe the bug**
After upgrading quickfixj to latest version (2.2.0) the code that used to run correctly now throws the following exception:
`Caused by: java.lang.IllegalArgumentException: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.
	at org.apache.xerces.jaxp.DocumentBuilderFactoryImpl.setAttribute(Unknown Source)
	at quickfix.DataDictionary.load(DataDictionary.java:883)
	at quickfix.DataDictionary.read(DataDictionary.java:869)`

**Expected behavior**
The same code should still be running after library update.

**system information:**
 - OS:Linux, Ubuntu 18.04 LTS
 - Java version JDK8
 - QFJ Version 2.2.0
 - Xerces version 2.12.0

**Additional context**
This is a piece of software that used to run correctly before, the only change we did was to upgrade the QFJ library. The application embeds QFJ functionality and also requires Xerces for additional functionalities, so we cannot get rid of Xerces or use an older version.

**Comment by chrjohn** [comment]
Closing as duplicate. 
#346 #306 
https://github.com/quickfix-j/quickfixj/issues?q=is%3Aissue+is%3Aclosed+xerces
