### ISSUE TITLE
how to reload order data when i restart server?

### ISSUE THREAD

**Issue by minikiller** [quickfix-j/quickfixj#355]
I found this url https://www.quickfixj.org/usermanual/2.1.0/usage/acceptor_failover.html, I create config file like this :
```
[default]
FileStorePath=target/data/ordermatch
DataDictionary=FIX42.xml
SocketAcceptPort=8323
BeginString=FIX.4.2
; for python used
TimeStampPrecision=MICROS
; for n2n used
; TimeStampPrecision=MILLIS
SenderCompID=FEME
ConnectionType=acceptor
StartTime=00:00:00
EndTime=00:00:00
FileLogPath=logs
AllowUnknownMsgFields=Y
ValidateUserDefinedFields=N
ValidateIncomingMessage=N
ValidateSequenceNumbers=N
RefreshMessageStoreAtLogon=Y
```
I try to add a new order, but when i restart server i found order data can not reload from persist data! How can i do in this tiem? thanks!

**Comment by chrjohn** [comment]
Please use the mailing list or StackOverflow for general help requests. See links here: https://github.com/quickfix-j/quickfixj/issues/new/choose

Don't forget to add some log output when asking there. Thanks!

**Comment by minikiller** [comment]
@chrjohn I had submit question to stackoverflow in this url:https://stackoverflow.com/questions/65756048/how-to-reload-order-data-when-i-restart-fix-server, but there are nobody reply for me. If you can solve this problem,please help me. Thanks!

**Comment by chrjohn** [comment]
There is a comment now on that SO question but no answer from you. ;)
