### ISSUE TITLE
RefreshOnLogon is applicable to Initiator

### ISSUE THREAD

**Issue by esanchezros** [quickfix-j/quickfixj#362]
Hi,

The `RefreshOnLogon` property seems to be applicable to the Initiator. In the documentation it only appears under the **Acceptor** section.

    FIXT.1.1:SenderCompId->TargetCompId: Refreshing message/state store on Logon

I was wondering if it should be moved to the **Miscellaneous** section or be duplicated in the **Initiator** section for clarity. Happy to create the PR if needed.

Thanks
Ed

**Comment by chrjohn** [comment]
Hi Ed,

it already is under the Misc section in master. :)
https://github.com/quickfix-j/quickfixj/pull/286

Thanks :)

**Comment by esanchezros** [comment]
Cool, thanks Chris
