### ISSUE TITLE
There is no connection timeout if host can't be reached.

### ISSUE THREAD

**Issue by cristipop93** [quickfix-j/quickfixj#363]
**Describe the bug**
I am implementing a simple desktop GUI application that should connect securely to a server. I want to handle the scenario where the host cannot be reached. I want to display a proper message to the user that the application is retrying to connect to the server, and after a while to stop connecting and display another message.

I implemented the SessionStateListener to handle the onDisconnect event hoping this will be called when the host is not reached.

**To Reproduce**
You can easily reproduce this with the Banzai application. You just need to type a host that does not exist in the cfg file at the SocketConnectHost property.
I have the ReconnectInterval set to 10. 
Right now, if the host cannot be reached it will throw an exception that I am not able to catch, java.nio.channels.UnresolvedAddressException, and then it retries connecting after 10 seconds without stopping after a number of attempts.

**Expected behavior**
Another property should say how many times it should try to reconnect until stopping and disconnecting,
Or some sort of a mechanism to limit the number of reconnect and stop it after a while and notify the SessionStateListener.

**system information:**
 - OS: Ubuntu 18
 - Java version JDK8
 - QFJ Version 2.1.1

**Comment by chrjohn** [comment]
I think this has some overlaps with #342 w.r.t. to the `SessionStateListener`.

Can't you implement the logic to stop reconnecting on your own? I.e. call `Initiator.stop()`? Or what would be the problem of this approach?

**Comment by cristipop93** [comment]
I was thinking that there might already exist some kind of mechanism that deals with this that I didn't find in the documentation.
I will implement this on my own.

**Comment by chrjohn** [comment]
Ok. If you feel there still is something missing apart from the stuff mentioned in the other issue just reopen. Thanks :)
