### ISSUE TITLE
Adding tips for importing the project into the IDE

### ISSUE THREAD

**Issue by felipewind** [quickfix-j/quickfixj#364]
**Is your feature request related to a problem? Please describe.**
I had some problems to open this project successfully into my IDE as described in [this topic in stackoverflow](https://stackoverflow.com/questions/65744671/quickfixj-setting-up-sources-for-development-could-not-find-artifact-org-quick/65745789#65745789).

**Describe the solution you'd like**
The project could have some documentation about how to import it to the IDE.

**Describe alternatives you've considered**
Would it be a good idea to add a tip on how to import the project into the IDE in the README.md?

I thought of adding a new topic `importing the project into the IDE` right after the `build instructions` topic.

The text would be like (copying the user manual):

```
When the project is first created, it will not have the generated message classes and compile errors will occur! 
Best is to compile once on the command line before importing the project into the IDE. 

If the IDE reports some errors after the compilation with "mvn clean package", try to use "mvn clean install", like:

$ mvn clean install -Dmaven.javadoc.skip=true -DskipTests -PskipBundlePlugin
```

If this idea is approved, I also thought about including the tip of using `mvn install` in the user manual in the `Building QuickFIX/J - IDE support` section. By the way, this sections states:

> There are Eclipse and Netbeans project definition files in the top-level directory of the checked out directory.

I didn't find this in the project, but maybe I didn't look it right. I just found a folder with some files to be used with `Eclipse` - `quickfixj/quickfixj-core/src/main/eclipse`. If this project definition files don't exist anymore, perhaps I could remove this sentence too, but forgive me if I'm wrong.

**Additional context**
User manual:

![image](https://user-images.githubusercontent.com/47837222/106370865-1156fb00-633d-11eb-83b5-83eba54f83b5.png)

**Comment by chrjohn** [comment]
:+1: 
You are right, the project definition files for Eclipse and Netbeans do not exist anymore. You could remove that sentence.
