### ISSUE TITLE
Add SessionID to SessionStateListener methods

### ISSUE THREAD

**Issue by esanchezros** [quickfix-j/quickfixj#365]
Apologies if this has been requested already but I think it will be great if the methods on `SessionStateListener` interface would accept the `Session` or the `SessionID` to identify which session has produced the event. At the moment, I have to pass the session to the state listener when adding the state listener to the session:

```
((SessionConnector) clientInitiator).getManagedSessions()
		.forEach(session -> session.addStateListener(new MonitoringSessionStateListener(session)));
```
...

```
public class MonitoringSessionStateListener implements SessionStateListener {

	private final Session session;

	MonitoringSessionStateListener(Session session) {
		this.session = session;
	}
```

Thanks
Ed

**Comment by chrjohn** [comment]
Sounds like a sensible enhancement to me. `SessionID` should be OK in my opinion.

**Comment by esanchezros** [comment]
OK, that's great. I will try to create a PR for this change. Thanks Chris
