### ISSUE TITLE
UtcTimestampConverter doesn't convert to UTC

### ISSUE THREAD

**Issue by nolag** [quickfix-j/quickfixj#372]
**Describe the bug**
The class simply takes a local date (for example provided by the Session on line 774).  The local date there is just the local date from the computer.

**To Reproduce**
Use a box that has timezone sent to anything but UTC.  Send a message.  The SendingTime field will be set to the local time not the UTC time even though the FIX protocol specifies UTC.

**Expected behavior**
The SendingTime is set to UTC time

**system information:**

Anything should work.  It's in the Java code, but my specs below.
 - OS: [e.g. Linux]  OSX
 - Java version [e.g. JDK8] 13
 - QFJ Version [e.g. 2.1.1] latest (pulled from master before making this)

**Additional context**

https://www.onixs.biz/fix-dictionary/4.2/tagNum_52.html specifies that it's UTC always, and the name of the convert function implies that was the intent.

I can make the fix in the converter, but want to confirm nothing else will break and that I'm not missing something obvious.

**Comment by chrjohn** [comment]
I cannot quite follow here unless I'm missing something. For example all of our servers are in CET/CEST timezone and correctly set the `SendingTime` to UTC using QuickFIX/J.

Session on line 774:
https://github.com/quickfix-j/quickfixj/blob/4d5401979b1046b68e2196aec37f56a6a3c46416/quickfixj-core/src/main/java/quickfix/Session.java#L774

This does not use the `UtcTimestampConverter` but uses `SystemTime`.

Could you please clarify?
Thanks :)

**Comment by nolag** [comment]
Sorry, I didn't trace the stack enough.  I had looked at the wrong thing when I made this.  Turns out I wasn't looking at what we were reading.  Please ignore.
