### ISSUE TITLE
Clarify thrown Exceptions in `SessionSettings`

### ISSUE THREAD

**Issue by chrjohn** [quickfix-j/quickfixj#378]
E.g. there is 

https://github.com/quickfix-j/quickfixj/blob/895224da1a05055bc99d936920d1e1ed7edc9935/quickfixj-core/src/main/java/quickfix/SessionSettings.java#L368-L374

but `FieldConvertError` is never thrown but wrapped into `ConfigError`.

Then there is 

https://github.com/quickfix-j/quickfixj/blob/895224da1a05055bc99d936920d1e1ed7edc9935/quickfixj-core/src/main/java/quickfix/SessionSettings.java#L306-L312

where `ConfigError` could be thrown by `getString`.

I think `getBool` (and other methods that have this behaviour) should be changed to not mask the `FieldConvertError` so that it is clear whether there is a problem with the key (i.e. setting was not found) or the value (i.e. value could not be converted).

**Comment by vinipx** [comment]
@chrjohn I would like to give it a try to fix it :)

**Comment by chrjohn** [comment]
@vinipx please go ahead 👍

**Comment by vinipx** [comment]
Apparently, only `getBool` method is currently masking/hiding the meaningful exception in `SessionSettings` class. 

@chrjohn 
would it be sufficient to simply cleanup the try/catch block and let `getString` throw it effectively in case of null value?

e.g.:
```
public boolean getBool(SessionID sessionID, String key) throws FieldConvertError, ConfigError {
            return BooleanConverter.convert(getString(sessionID, key));
}
```
