### ISSUE TITLE
Make `DataDictionary.getVersion()` return version including service pack

### ISSUE THREAD

**Issue by chrjohn** [quickfix-j/quickfixj#381]
Follow-up to #258 where `getVersion()` was not changed for a minor QFJ release. But with 3.0.0 we should change this.

**Comment by vinipx** [comment]
@chrjohn I can work on this one, may I? 

How would you like to see it? beginString + servicePack? any preferable format?

example:
``` java
public String getVersion() {
       return beginString + valueOf(servicePack); // or valueOf(getServicePack())
}
```

Also, should we change the `getFullVersion` ?

**Comment by chrjohn** [comment]
Closed. See https://github.com/quickfix-j/quickfixj/pull/579#issuecomment-1346438667
