### ISSUE TITLE
#376 breaks AcceptorTemplate

### ISSUE THREAD

**Issue by jimbogithub** [quickfix-j/quickfixj#385]
**Describe the bug**
https://github.com/quickfix-j/quickfixj/pull/376 appears to break AcceptorTemplates.  Specifically the moving of this line:

`AcceptorSocketDescriptor descriptor = getAcceptorSocketDescriptor(settings, sessionID);`

in `quickfix.mina.acceptor.AbstractSocketAcceptor` to inside the ` if (!isTemplate) {` block means that the later

```
 if (socketDescriptorForAddress.isEmpty()) {
    throw new ConfigError("No acceptor sessions found in settings.");
 }
```

always throws an error if the only Session is the template.

**Comment by chrjohn** [comment]
Hi @jimbogithub , thanks for catching this. :+1: 
Would've been bad if this got into the release. Seems the test coverage around the AcceptorTemplate is insufficient. Will take a look at it.

**Comment by chrjohn** [comment]
https://github.com/quickfix-j/quickfixj/blob/1126a4f782f173566baa9dd0a5f1590601d82392/quickfixj-core/src/main/java/quickfix/mina/acceptor/AbstractSocketAcceptor.java#L241-L242

Unfortunately `getAcceptorSocketDescriptor()` adds a descriptor to a map which was unexpected for me when reading the method name. :-/

**Comment by chrjohn** [comment]
Opened #386 which currently only contains unit test to highlight problematic behaviour. Will add rest later.

**Comment by jimbogithub** [comment]
> Are you able to test a fix?

Yes, I have a test in my own system that will pass/fail this.

**Comment by chrjohn** [comment]
Great, will merge in the next two hours or so. Guess that will not make things worse.

**Comment by chrjohn** [comment]
@jimbogithub , I have merged now.

**Comment by jimbogithub** [comment]
@chrjohn Thanks, my tests pass.

**Comment by chrjohn** [comment]
Great, thanks for the heads-up. :+1:
