### ISSUE TITLE
Website documentation has been removed (404)

### ISSUE THREAD

**Issue by drosser** [quickfix-j/quickfixj#396]
**Describe the bug**
Website documentation has been moved/is down. Links on both 2.1.0 and 2.0.0 are now invalid.

**To Reproduce**
Navigate to any documentation link, e.g. https://www.quickfixj.org/usermanual/2.1.0/usage/configuration.html

**Expected behavior**
Site loads with documentation

**system information:**
N/A

**Additional context**
![image](https://user-images.githubusercontent.com/30077615/118556646-098c5c80-b75c-11eb-8c32-67497426a2d1.png)

**Comment by chrjohn** [comment]
Oh sorry, we changed it so that only the current doc is available. Most of the time there are only minimal changes to that file. Is that a big problem for you?
You could always access the file `configuration.html` in the source tree (for the specific release tag) here on github and it is also packaged with the binary distribution.
I'll see if I can make it available somehow via github pages.

**Comment by chrjohn** [comment]
https://htmlpreview.github.io/?https://github.com/quickfix-j/quickfixj/blob/QFJ_RELEASE_2_1_1/quickfixj-core/src/main/doc/usermanual/usage/configuration.html
Does this help?

**Comment by drosser** [comment]
Hey @chrjohn, thanks for getting back to me! 

To be honest, I'm unsure - we're currently using QFJ `2.1.1`, but I've seen (in passing) in `2.3.0` you support functional interfaces for receiving messages, so my plan is to try and bump up to `2.3.0` so I can take advantage of it (although I can see it was added in `2.2.0`). However, I'd only spotted it accidentally after trying to determine if any of the documentation links worked (I suspected deprecation of older documentation). I think I need to do more digging into what features were added in `2.2.0` and `2.3.0`, as I suspect there was just more than that.

RE: https://www.quickfixj.org/documentation/index.html, ultimately it only showed version `2.0.0` and `2.1.0` whereas I know QuickfixJ is currently on version `2.3.0` by checking https://github.com/quickfix-j/quickfixj/wiki - Should I assume that the quickfixj.org site is not maintained any more and only refer to the Github?

**Comment by chrjohn** [comment]
You can always check what changed in a release by looking at the release notes in the wiki.
https://github.com/quickfix-j/quickfixj/wiki/QFJ-2.2.0-release-notes which has a link to all resolved issues/PRs: https://github.com/quickfix-j/quickfixj/milestone/8?closed=1

quickfixj.org is still maintained but I need to tell the guys maintaining it to update the links to the docs. Eventually the website should be moved to github pages (see #237) but need to find time for that... But in general I would suggest to always look on github to find the most current information.

**Comment by chrjohn** [comment]
Oh and BTW, regarding the functional interfaces: you can see how it is used right on the main page: https://github.com/quickfix-j/quickfixj#functional-interfaces-for-receiving-messages
