### ISSUE TITLE
Deadlock while using SSL + Proxy

### ISSUE THREAD

**Issue by JosephP91** [quickfix-j/quickfixj#398]
Hi all! I found a deadlock while looking at this thread dump. It seems to be related to SSL and proxy.

https://www.dropbox.com/s/4bpyevdcrbdgmya/thread-dump-clean.txt?dl=0

**Comment by chrjohn** [comment]
I know. I commented on your StackOverflow post. :)

**Comment by chrjohn** [comment]
Probably the best we can do is to open a MINA bug. But I saw there still is one related report open with them which sounds similar.

**Comment by JosephP91** [comment]
Yes, are you referring to this? https://issues.apache.org/jira/browse/DIRMINA-1119

**Comment by chrjohn** [comment]
Yes that is the one.

**Comment by JosephP91** [comment]
I openend a new one and attached the thread dump: https://issues.apache.org/jira/plugins/servlet/mobile#issue/DIRMINA-1144

**Comment by chrjohn** [comment]
Thank you.

**Comment by JosephP91** [comment]
I can confirm that the mina-core 2.0.20 version is working. So basically, if you exclude mina-core from quickfix dependency inside pom.xml file and include the 2.0.20 version, it should be fine. Since this is not a quickfix bug, I think I can close the issue. Feel free to reopen it for further problems.

**Comment by chrjohn** [comment]
Thanks for analysing this. It is good to know that 2.0.20 does not have this bug. Would be interesting to know why but I hope the MINA guys will come up with something.

**Comment by swapnilgupta10** [comment]
@JosephP91 i have similar issue which i downgraded to 2.0.23 but still figuring dead lock issue. Wondering what led us to 2.0.20 to make sure it's working.? Do we have any release not for this issue to occur after any specific version?

**Comment by chrjohn** [comment]
This hopefully should be fixed with MINA 2.2.x
See https://github.com/quickfix-j/quickfixj/pull/635

**Comment by swapnilgupta10** [comment]
@chrjohn Thanks for quick update.
As per your above pull request, look like we need mina version upgrade along with few changes in quick fix api.
Do we have any ETA to new release version for above change? Will this required jdk higher version than 1.8 +?

**Comment by chrjohn** [comment]
MINA 2.2.2 is still JDK8, otherwise #635 could not have been built.

**Comment by chrjohn** [comment]
I have merged the changes into https://github.com/quickfix-j/quickfixj/tree/QFJ_2_3_x
Are you able to build a release from there and test it?

**Comment by swapnilgupta10** [comment]
Sure, I'll give a try. You mean build a snapshot release on my local and test?

**Comment by x-leviathan** [comment]
Hi @chrjohn 
Does recent released version 2.3.2 fix this deadlock bug? I notice quickfixj 2.3.2 uses Mina 2.2.4

**Comment by chrjohn** [comment]
https://github.com/quickfix-j/quickfixj/discussions/774#discussioncomment-11522693

**Comment by x-leviathan** [comment]
Got it. Thanks. I will try to perform integration testing locally to verify.
