### ISSUE TITLE
Float numbers are interpreted with a comma as separator for thousand 

### ISSUE THREAD

**Issue by franck54730** [quickfix-j/quickfixj#407]
**Describe the bug**
If I put a value higher than 999 in a field of the FIX message the parser get this value with a comma as thoushand 

**To Reproduce**

This implementation :

`
			DefaultDataDictionaryProvider defaultDataDictionaryProvider = new DefaultDataDictionaryProvider();
			DataDictionary dataDictionary = defaultDataDictionaryProvider.getApplicationDataDictionary(getAppVerID(fixVersion));
			MessageFactory messageFactory = new DefaultMessageFactory();
			Message parsedMessage = MessageUtils.parse(messageFactory, dataDictionary, preparedInput);
			return new FixMessageWrapper(parsedMessage, dataDictionary);
` 

With this fix message for example : 

`8=FIX.4.4|9=323|35=8|34=3|52=20210726-10:00:31|49=ULLINK|56=T24|37=S6QMxZ1N-00|11=OPODSC2120777994|447=JBBRFRPP|17=0000000098|150=F|39=2|55=1 1 DRILLISCH EUR 0 BR REG|48=DE0005545503|22=4|461=EXXXXX|167=CS|54=1|38=1200|40=1|423=2|15=EUR|59=6|432=20210729|528=A|32=1200|31=24.44|30=XOFF|29=1|151=0|14=1200|6=24.44|60=20210726-10:00:21|21=3|10=103|`

In the Dictionnary, value for field 32 is "1,200" instead of "1200"

**Expected behavior**
This field should be treated without the comma

**system information:**
 - OS: Linux
 - Java version : JDK8
 - QFJ Version : 2.2.0

**Additional context**
I didn't find any configuration to not use the english number writting and so on remove the comma, could you help me with this ?

**Comment by chrjohn** [comment]
What is the class FixMessageWrapper? Are you doing something with the message there? Can you compare the value in the message right after it has been parsed?

**Comment by chrjohn** [comment]
IMHO this should work using QFJ classes. I don't know what `FixMessageWrapper` is but I think it is causing the real problem. Otherwise please add some kind of unit test that exhibits the problem.

Thanks :)
