### ISSUE TITLE
removeGroup leaves entry in groups

### ISSUE THREAD

**Issue by philipwhiuk** [quickfix-j/quickfixj#413]
https://github.com/quickfix-j/quickfixj/blob/9df0fe1334b56449a448a985b80df77acae3813b/quickfixj-core/src/main/java/quickfix/FieldMap.java#L672

Why do we clear the list of groups rather than just do:

```
this.groups.remove(field);
```

Is there some purpose behind this?

**Comment by philipwhiuk** [comment]
This means the following code:

```
```
Message m = new Message();
Group group = new Group(73,11);
m.addGroup(group);
m.removeGroup(73);
System.out.println(m.hasGroup());
```
will print true, not false

**Comment by chrjohn** [comment]
There also is this:

https://github.com/quickfix-j/quickfixj/pull/163

**Comment by philipwhiuk** [comment]
Yeah - I'm unconvinced there's a reason for the extra method - we should just fix the original method. I'll submit a small PR and close off #163

**Comment by philipwhiuk** [comment]
Yeah - I'm unconvinced there's a reason for the extra method - we should just fix the original method. I'll submit a small PR and close off #163

**Comment by philipwhiuk** [comment]
Yeah - I'm unconvinced there's a reason for the extra method - we should just fix the original method. I'll submit a small PR and close off #163

**Comment by chrjohn** [comment]
I am almost sure there was an old JIRA issue for this problem but JIRA is down. Might add the reference later.
