### ISSUE TITLE
Cannot establish two fix connections to two different clients in same classloader

### ISSUE THREAD

**Issue by kotari4u** [quickfix-j/quickfixj#428]
Hi, We are working on a project in a bank where we are using this quick fix api and connect to two different vendors via fix connectivity. The way we are trying to do is in different spring context we provide two different fix connections. But we are facing issue where we are able to connect to only one client and other one is being ignored. It is working fine if we load the spring context on different class loader or other jams

Upon debugging this issue we have realized that the issue is with quickfix.mina.SessionConnector class

In this class there is "private static final" executor service and that is allowed only one for class loader. There is no way to override. We tried shortLivedExecutor in the same class but it did not work. Is there any if we can make this "private final" and make it unique per class so that we can connect to different fix connections. Do you see any issues with this approach ? Trying to understand what would be the reason behind making it "static"

**Comment by chrjohn** [comment]
Hi,
sorry, I don't have any experience with QFJ on Spring so please excuse my possibly ignorant statements. :) You are using the "normal" Spring (not Spring Boot)?

The standard way to connect to separate FIX connections would be either to configure one Initiator with several sessions or use several separate Initiators with one session each. Isn't this possible in your case?

But actually I don't see how the executor service should prevent you from having different FIX connections? All it does is to iterate over all Sessions and triggers a timer event. But maybe Spring handles some things differently here?
Thanks,
Chris.

**Comment by esanchezros** [comment]
Hi @kotari4u,

Further to @chrjohn explanation, I'd like to clarify something. What do you mean by `in different spring context we provide two different fix connections`? 

In your Spring context you must have configured an `Initiator` bean (either a `SocketInitiator` or a `ThreadedSocketInitiator`) and provided a `SessionSettings` where the session settings are configured. In that file you can specify as many sessions as you need. If you have two different Spring contexts you would have defined two separate `Initiator` beans and two separate `SessionSettings`. 

Are you configuring the `SocketConnectHost`, `SocketConnectPort`, etc, of the vendors in the configuration file?

We use Spring and Spring Boot with QuickFixJ and multiple sessions to different vendors, never found an issue.

Thanks
Ed
