### ISSUE TITLE
Add affected `socketAddress` to `SessionStateListener#onConnectException`

### ISSUE THREAD

**Issue by stasal** [quickfix-j/quickfixj#450]
Please, consider adding `socketAddress` to exception passed as argument for `quickfix.SessionStateListener#onConnectException`

This information is available in `quickfix.mina.initiator.IoSessionInitiator.ConnectTask#handleConnectException` method and it can be very useful for troubleshooting outside the library

**Comment by chrjohn** [comment]
sounds like a sensible enhancement. Are you able to submit a PR for this?

**Comment by stasal** [comment]
@chrjohn Sure! Opened a pull request, take a look. Maybe I need to implement some tests for new code?

**Comment by chrjohn** [comment]
Thanks for the PR, let's continue the discussion there.
