### ISSUE TITLE
Enhance exception type and message in `FieldMap` class `setField()` method

### ISSUE THREAD

**Issue by amin-moradi** [quickfix-j/quickfixj#458]
This is an enhancement.
In class FieldMap, method setField(StringField field) throws a NullPointerException, but it does not mention which field:
`throw new NullPointerException("Null field values are not allowed.");`

I would suggest to throw an exception like following to mention the field name and also a better exception type like FieldException:
`throw new FieldException(SessionRejectReason.NULL_DATA_FOR_VALUE,
                    field.getField());`

**Comment by chrjohn** [comment]
Sounds like a sensible enhancement. Are you able to provide a PR?
Thanks

**Comment by vinipx** [comment]
> Sounds like a sensible enhancement. Are you able to provide a PR? Thanks

@chrjohn I would like to give it a try to fix it :)

**Comment by chrjohn** [comment]
@vinipx great, thanks 👍
