### ISSUE TITLE
Required Tag Missing error on version changed

### ISSUE THREAD

**Issue by felipedelta0** [quickfix-j/quickfixj#473]
**Describe the bug**
After migrating from quickfixj-all 1.5 to 2.3.1, on receiving an Execution Report, I got "Required tag missing, tag=453", but on another service that is using 1.5, it doesn't happen, only on 2.3.1.

**To Reproduce**
Send new order and receive execution report without tag 453

**Expected behavior**
Proceed to process the message.

**system information:**
 - OS: Linux Ubuntu
 - JDK8
 - Quickfixj 2.3.1

**Comment by chrjohn** [comment]
But does the message contain tag 453? Please provide an example message. Are you using the data dictionary that is shipped with QFJ? What does your config look like?

**Comment by felipedelta0** [comment]
> But does the message contain tag 453? Please provide an example message. Are you using the data dictionary that is shipped with QFJ? What does your config look like?

It doesn't have this tag on the message.
I haven't changed the configuration on migrating the version, neither the dictionary.
But on version 1.5 it works without changing anything.
I don't have a message example now, but I'll update with it later.

**Comment by chrjohn** [comment]
> I haven't changed the configuration on migrating the version, neither the dictionary.

Please provide the config. Please state if it is a dictionary shipped with QFJ or a custom one.

> But on version 1.5 it works without changing anything.

Bugs get fixed (or introduced) between versions, the dictionaries shipped with QFJ could change between versions (when there were tags missing for example).

**Comment by chrjohn** [comment]
Please reopen when the asked information can be provided. Thanks :)
