### ISSUE TITLE
How to add new values in tag 528 in FIX 5.0sp01?

### ISSUE THREAD

**Issue by lunaatlasifs** [quickfix-j/quickfixj#478]
Tag 47 was replaced by tag 528 but the codes in Tag 47 were not all ported to tag 528 especially value L.  Trade orders are rejected with this message. 
error> (Reject sent for Message 103: Value is incorrect (out of range) for this tag, field=528:528) . 528=L is now getting sent by the exchange. Exchange recommended updating the data dictionary. We are java defined functions in QuickFix/J.  Can you please advise on how to add these values for tag 528?  Can we just simply modify the OrderCapacity super (528)?

S – Institutional
G – Group
O – Other
M – Market Maker
L – Related Party
E – Error
T – Tax Exempt
D – Special Account Retail
F – Special Account Institutional

**Comment by codeicu** [comment]
Modify your FIX 5.0sp01.xml
