### ISSUE TITLE
`LostLogoutTest`, `LostLogoutThreadedTest`, `SocketAcceptorTest` use a fixed port

### ISSUE THREAD

**Issue by chrjohn** [quickfix-j/quickfixj#487]
This should be changed to a dynamic port to prevent `BindExceptions` because that port is already in use.

See for example
https://github.com/quickfix-j/quickfixj/blob/48ea859f55904643a9059b91b37611e4424c6248/quickfixj-core/src/test/java/quickfix/SocketAcceptorTest.java#L208

**Comment by isurudevj** [comment]
hi @chrjohn 

I made a pull request for this.

https://github.com/quickfix-j/quickfixj/pull/573

**Comment by chrjohn** [comment]
Thanks @isurudevj , will take a look.
