### ISSUE TITLE
Quickfixj giving error of nullpointer of socket accpet address parameter when we add session targetcompid as MKTREC28

### ISSUE THREAD

**Issue by vaibhavshah1** [quickfix-j/quickfixj#490]
When we are adding multiple sessions in sell session config file and run quickfixj. It is working properly. However, it is giving socket accept address null pointer exception if we add targetcompid as = MKTREC28. If we use double qoutes if word is conflicting somewhere then it is expecting targetcompid with double quotes as well. This is creating problem. Please help to understand issue and solve ASAP. Thanks.

**Comment by chrjohn** [comment]
Don't know why that should be a reserved keyword somewhere on QFJ. Could you post the complete stack trace of the NPE?

**Comment by chrjohn** [comment]
Is that the complete stack trace? Is your settings file truncated?

**Comment by vaibhavshah1** [comment]
TCS Confidential

Dear Christoph,

Thanks for the reply. Here is sell session config file we are using:


[DEFAULT]
BeginString=FIXT.1.1
ConnectionType=acceptor
SenderCompID=SGXICI
UseDataDictionary=Y
ResetOnDisconnect=N
ResetOnLogout=N
ValidateUserDefinedFields=Y
ValidateFieldsHaveValues=Y
#TimeStampPrecision=SECONDS
TimeStampPrecision=MILLIS
DefaultApplVerID=9
CheckLatency=N
EnableNextExpectedMsgSeqNum=N
PersistMessages=N

FileStorePath=/home/fixengine/tcs/data/client/ror
#FixnetFileLogPath=/home/Log
FixnetLog4jPropertyFile=/home/fixengine/tcs/src/main/resources/sell/log4j2.properties
FixnetFileLogHeartbeats=Y
FixnetFileIncludeMilliseconds=Y
#FixnetFileIncludeTimeStampForMessages=Y
#FixnetFileLogTimezone=GMT+05:30
SLF4JLogPrependSessionID=N

SocketAcceptAddress=12.12.123.12
#AllowedRemoteAddresses=
SocketAcceptPort=8007
TimeZone=GMT+05:30
#StartDay=Monday
#EndDay=Friday
# FO_20220530 - New Settings
#StartTime=03:35:00
#EndTime=03:30:00
StartTime=04:00:00
EndTime=03:30:00
HeartBtInt=60
ReconnectInterval=5
MillisecondsInTimeStamp=N
DataDictionary=/home/fixengine/core/src/main/resources/FIX50.xml
TransportDataDictionary=/home/fixengine/core/src/main/resources/FIX50.xml
AppDataDictionary=/home/fixengine/core/src/main/resources/FIX50.xml

#[storage]
#JdbcDriver=oracle.jdbc.driver.OracleDriver
***@***.***
#JdbcUser=ABCDEF
#JdbcPassword=ABCDEFGHIJKLMNOPQRSTUVWXYZ
#JdbcMaxActiveTime=65534
#ExtendedSessionIdSupported=N

[session]
TargetCompID=MKTREC01

[session]
TargetCompID=MKTREC02

[session]
TargetCompID=MKTREC03

[session]
TargetCompID=MKTREC04

[session]
TargetCompID=MKTREC05

[session]
TargetCompID=MKTREC06

[session]
TargetCompID=MKTREC07

[session]
TargetCompID=MKTREC08

[session]
TargetCompID=MKTREC09

[session]
TargetCompID=MKTREC10

[session]
TargetCompID=MKTREC11

[session]
TargetCompID=MKTREC12

[session]
TargetCompID=MKTREC13

[session]
TargetCompID=MKTREC14

[session]
TargetCompID=MKTREC15

[session]
TargetCompID=MKTREC16

[session]
TargetCompID=MKTREC17

[session]
TargetCompID=MKTREC18

[session]
TargetCompID=MKTREC19

[session]
TargetCompID=MKTREC20

[session]
TargetCompID=MKTREC21

[session]
TargetCompID=MKTREC22

[session]
TargetCompID=MKTREC23

[session]
TargetCompID=MKTREC24

[session]
TargetCompID=MKTREC25

[session]
TargetCompID=MKTREC26

[session]
TargetCompID=MKTREC27

[session]
TargetCompID=MKTREC28

[session]
TargetCompID=MKTREC29

[session]
TargetCompID=MKTREC30

[session]
TargetCompID=MKTREC31

[session]
TargetCompID=MKTREC32

[session]
TargetCompID=MKTREC33

[session]
TargetCompID=MKTREC34

[session]
TargetCompID=MKTREC35

[session]
TargetCompID=MKTREC36

[session]
TargetCompID=MKTREC37

[session]
TargetCompID=MKTREC38

[session]
TargetCompID=MKTREC39

[session]
TargetCompID=MKTREC40

[session]
TargetCompID=MKTREC41

[session]
TargetCompID=MKTREC42

[session]
TargetCompID=MKTREC43

[session]
TargetCompID=MKTREC44

[session]
TargetCompID=MKTREC45

[session]
TargetCompID=MKTREC46

[session]
TargetCompID=MKTREC47

[session]
TargetCompID=MKTREC48

[session]
TargetCompID=MKTREC49

#[session]
#TargetCompID=MKTREC50

#[session]
#TargetCompID=MKTREC51

#[session]
#TargetCompID=MKTREC52

#[session]
#TargetCompID=MKTREC53

#[session]
#TargetCompID=MKTREC54

#[session]
#TargetCompID=MKTREC55

#[session]
#TargetCompID=MKTREC56

#[session]
#TargetCompID=MKTREC57

#[session]
#TargetCompID=MKTREC58

#[session]
#TargetCompID=MKTREC59

#[session]
#TargetCompID=MKTREC60


Regards,
Vaibhav Shah

**Comment by chrjohn** [comment]
Actually I asked for the complete stack trace. :)

**Comment by chrjohn** [comment]
Please come back with the asked information if there still are problems.

**Comment by chrjohn** [comment]
Is that the complete stack trace? Is your settings file truncated?
