### ISSUE TITLE
"|" character in counterparty memo

### ISSUE THREAD

**Issue by ksushant881** [quickfix-j/quickfixj#553]
"|" is unsupported for Counterparty memo at the time. Can it be fixed?

**Comment by chrjohn** [comment]
Sorry typed too fast. 54 is character field. Can you point to where pipe is used for tag 54?

**Comment by chrjohn** [comment]
Why shouldn't they be able to?

**Comment by chrjohn** [comment]
Please reopen once you have the needed information.
