### ISSUE TITLE
Remove "if else" statements which is slower by nearly 7 times compared to `HashMap` in generated `MessageCracker` class

### ISSUE THREAD

**Issue by busy-spin** [quickfix-j/quickfixj#577]
**Describe the bug**
MessageCracker generated class contains a lengthy if else statement to resolve the method call for the respective  message type.
Current logic is about 7 times slower than using HashMap key'd by message type and value as  the method reference.

I wrote a new MessageCracker.xsl which use the HashMap to resolve the method respective to message type. 

Following is the JMH benchmarking results.

### Before:

benchmarkCrackingGenerated    - use the current MessageCracker.xls generated class
benchmarkCrackingWithHashMap  use custom MessageCracker class which use HashMaps to resolve methods

Benchmark                                              Mode  Cnt         Score         Error  Units
MessageCrackerBenchmark.benchmarkCrackingGenerated    thrpt    5  10**923194**.106 ± 2861197.934  ops/s
MessageCrackerBenchmark.benchmarkCrackingWithHashMap  thrpt    5  69**723897**.515 ± 3242125.694  ops/s

### After:

benchmarkCrackingGenerated    - use the new MessageCracker.xls generated class
benchmarkCrackingWithHashMap  use custom MessageCracker class which use HashMaps to resolve methods

Benchmark                                              Mode  Cnt         Score          Error  Units
MessageCrackerBenchmark.benchmarkCrackingGenerated    thrpt    5  71**897498**.754 ± 19147681.365  ops/s
MessageCrackerBenchmark.benchmarkCrackingWithHashMap  thrpt    5  72**165054**.010 ±  4905711.116  ops/s

**To Reproduce**
Run my JMH benchmark code in my forked repo for QFJ

### Before
[Before Code Benchmark](https://github.com/isurudevj/quickfixj/blob/feature/new-message-crakcer-stage1/quickfixj-performance-regression/src/main/java/org/quickfixj/MessageCrackerBenchmark.java)

### After
[After Code Benchmark](https://github.com/isurudevj/quickfixj/blob/feature/new-message-cracker/quickfixj-performance-regression/src/main/java/org/quickfixj/MessageCrackerBenchmark.java)

**Expected behavior**
N/A

**system information:**
 - OS: [Windows11]
 - Java version [JDK8]
 - QFJ Version [3.0.0-SNAPSHOT]

**Additional context**
N/A

**Comment by isurudevj** [comment]
I made a PR for this , https://github.com/quickfix-j/quickfixj/pull/578
