### ISSUE TITLE
Quickfix parse error when Inconsistent SecurityDataLen <Tag 90> with SecurityData<Tag 91>

### ISSUE THREAD

**Issue by taneryilmaz** [quickfix-j/quickfixj#591]
When _SecurityDataLen_ is inconsistent (bigger value) with length of _SecurityData_ Quickfix parses message header wrongly.
For example;
SecurityData value has 5 characters data and SecurityDataLen is 8 characters, Quickfix parses tag value of SecurityData by concating following bytes. 

**To Reproduce**

**NewOrderSingle:**
![image](https://user-images.githubusercontent.com/1517859/208848899-04438190-f017-423c-b88c-9346caec80a1.png)

**Code debug:**
![image](https://user-images.githubusercontent.com/1517859/208850871-38b167e3-5fa0-4c1b-98af-8378a99aba49.png)

**Reject Response:**
![image](https://user-images.githubusercontent.com/1517859/208852256-fc1b25b5-5d4e-4ca5-9729-64119940f9a8.png)

**System information:**
 - Java version 11
 - QFJ Version 2.3.1

**Comment by chrjohn** [comment]
Hmm what else could we do? We must rely on the specified length. If the other side sends garbage we cannot really do much about it.

**Comment by taneryilmaz** [comment]
A consistency check _length of SecurityData_ with _SecurityDataLen_ is possible? If the lenghts are different a reject can be thrown.

**Comment by chrjohn** [comment]
How should we know when content of SecurityData is over?

**Comment by chrjohn** [comment]
Explanation from the spec:

> String field containing raw data with no format or content restrictions. Data fields are always immediately preceded by a length field. The length field should specify the number of bytes of the value of the data field (up to but not including the terminating SOH).
> Caution: the value of one of these fields may contain the delimiter (SOH) character. Note that the value specified for this field should be followed by the delimiter (SOH) character as all fields are terminated with an "SOH".

So IMHO there is no way of knowing when the data field has ended, so we cannot do any consistency checks. The only consistency check I could think of is whether the length of the data field is shorter than the length of the message, but don't know if that is sensible.

Please feel free to re-open when you have an idea what could be done. Thank you.

**Comment by taneryilmaz** [comment]
Ok, thanks @chrjohn
