### ISSUE TITLE
java.lang.NoClassDefFoundError: quickfix/MessageFactory error when trying to run the Banzai application

### ISSUE THREAD

**Issue by sangbida** [quickfix-j/quickfixj#605]
I've cloned the quickfixj repo and I've been trying to run the Banzai application. I'm using intelliJ ultimate as the IDE.

I ran: `mvn clean`  `mvn compile package` `java -jar target/quickfixj-examples-banzai-3.0.0-SNAPSHOT.jar
`
The first 2 commands run successfully, however, when running the last command from the terminal I get the following error: Error: Unable to initialize main class quickfix.examples.banzai.Banzai Caused by: java.lang.NoClassDefFoundError: quickfix/MessageFactory 

I haven't made changes to any pom.xml files or any other code in the repo. 

Compiling the quickfixj-core module also produces a lot of errors: 

`[INFO] BUILD FAILURE  
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  19:11 min 
[INFO] Finished at: 2023-01-19T13:11:08+10:00 
[INFO] ------------------------------------------------------------------------ 
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.4.1:jar (attach-javadocs) on project  quickfixj-core: MavenReportException: Error while generating Javadoc:  
[ERROR] Exit code: 1 - Loading source file /Users/sangbida/Development/polyrepo/quickfixj/quickfixj- core/src/main/java/org/quickfixj/CharsetSupport.java... 
[ERROR] Loading source file /Users/sangbida/Development/polyrepo/quickfixj/quickfixj- core/src/main/java/org/quickfixj/SimpleCache.java... 
`
The stack dump is too big so I won't add it all here, there are a lot of errors like this as well when compiling the quickfixj-core module: 
`[ERROR] /Users/sangbida/Development/polyrepo/quickfixj/quickfixj-core/src/main/java/quickfix/SessionID.java:26: error: cannot find symbol
[ERROR] import quickfix.field.BeginString;
[ERROR]                      ^
[ERROR]   symbol:   class BeginString
[ERROR]   location: package quickfix.field
`

**system information:**
 - OS: MacOS
 - Java version: openjdk 17.0.2
 - QFJ Version: Version: 3.0.0-SNAPSHOT

**Comment by chrjohn** [comment]
Did you check the build instructions here https://github.com/quickfix-j/quickfixj#build-instructions and here https://github.com/quickfix-j/quickfixj#importing-the-project-into-the-ide ?

Apart from that the `NoClassDefFoundError` originates from missing this class on the classpath. There are standalone JARs for the examples that should contain all needed classes. E.g. `quickfixj-examples-banzai-3.0.0-SNAPSHOT-standalone.jar`

If you still have questions please reopen. Thanks.
