### ISSUE TITLE
Throttling of admin messages

### ISSUE THREAD

**Issue by ajinkyatankhiwale1510** [quickfix-j/quickfixj#626]
Dear All,

We are using Quick FIX engine and we want to use Throttling on Admin messages. Can anyone please help on this? 

To Reproduce
Send admin messages with very high frequency(i.e. - more than 100 messages in 30 seconds )

Expected behavior
In case of more than 100 messages per 30 seconds, it should be rejected with business message rejection(msgType j).

System information:

OS: Red Hat Enterprise Linux 8.6 (Ootpa)
Java version : openjdk 11
QFJ Version 2.3.0
Additional context
NA.

**Comment by chrjohn** [comment]
I think this could be implemented in your `fromApp` or `fromAdmin` callback. QFJ offers no out-of-box solution for this.

Also see https://github.com/quickfix-j/quickfixj/issues/271.
