### ISSUE TITLE
DataDictionary.isHeaderField(tag) is returning false for valid header tags when used with 5.0SP2 dictionary

### ISSUE THREAD

**Issue by cestunefolie** [quickfix-j/quickfixj#627]
**Describe the bug**
method on class DataDictionary called isHeaderField(tag) is returning false for valid header tags when using dictionary FiIX5.0SP2.xml 

**To Reproduce**

    @Test
    void validatedHeaderFieldsForFIX50SP2Dictionary() throws ConfigError {
        DataDictionary fix50dictionary = new DataDictionary("FIX50SP2.xml");
        org.junit.jupiter.api.Assertions.assertTrue(fix50dictionary.isHeaderField(BodyLength.FIELD));
        org.junit.jupiter.api.Assertions.assertTrue(fix50dictionary.isHeaderField(BeginString.FIELD));
    }

**Expected behavior**
method in question should have returned true for valid Header tags as per dictionary specification

**system information:**
 - OS: Windows
 - Java version JDK17
 - QFJ Version 2.3.1

**Additional context**

**Comment by the-thing** [comment]
Have a look at the file. <header/> section is empty so I think this is the right behaviour.
