### ISSUE TITLE
`NonStopSession` is reported as a daily session

### ISSUE THREAD

**Issue by msmat0** [quickfix-j/quickfixj#648]
**Describe the bug**
The configuration contains NonStopSession=Y but the log still says:
schedule is daily, 00:00:00-UTC - 00:00:00-UTC
The problem seems to be in the method DefaultSessionSchedule.formatTimeInterval() which does not consider the NonStopSession setting.

**Comment by chrjohn** [comment]
So it is only a display problem but otherwise works as expected?

**Comment by msmat0** [comment]
As far as I can say it is working as expected. It only caused a lot of confusion when I saw in the log file that the session is still a daily session.

**Comment by chrjohn** [comment]
Would you like to create a PR @msmat0 ?

**Comment by msmat0** [comment]
Yes, I'm going to create PR for it.

**Comment by msmat0** [comment]
@chrjohn It seems I don't have the permission to push the code in my own branch.

**Comment by chrjohn** [comment]
That is strange. A lot of people are creating pull requests without me having to explicitly approve it. What exactly did you do?

**Comment by the-thing** [comment]
I think he might have created a branch in the quickfix-j/quickfixj repository and not in his own fork.

**Comment by msmat0** [comment]
I created a branch locally and did my changes in the code. After that I do:
`git push --set-upstream origin msmat0-nonstopsession-log-fix`
Then I'm asked to authenticate in Gitlab and the output is:
```
info: please complete authentication in your browser...
remote: Permission to quickfix-j/quickfixj.git denied to msmat0.
fatal: unable to access 'https://github.com/quickfix-j/quickfixj/': The requested URL returned error: 403
```

**Comment by chrjohn** [comment]
@msmat0 looks like it is as @the-thing suggested:

```
Pushing to ssh://github.com/quickfix-j/quickfixj
```

You are trying to push to quickfixj project directly and not to an own fork.

**Comment by msmat0** [comment]
@chrjohn I have forked the project and created a pull request #658
