### ISSUE TITLE
store message that contains Chinese charset in filestore will be truncated

### ISSUE THREAD

**Issue by pyy07** [quickfix-j/quickfixj#650]
**Describe the bug**
Store message that contains Chinese charset in filestore will be truncated when retrieved (it happens when is required to resend messages)

**To Reproduce**
Steps to reproduce the behavior.
Or even better, a unit test or reproducer.

```
void test() {
    CharsetSupport.setCharset("UTF-8");
    ExecutionReport executionReport = new ExecutionReport(
                    new OrderID("123"),
                    new ExecID("123"),
                    new ExecTransType(ExecTransType.CANCEL),
                    new ExecType(ExecType.CANCELED),
                    new OrdStatus(OrdStatus.CANCELED),
                    new Symbol("000000"),
                    new Side(Side.BUY),
                    new LeavesQty(1000.0),
                    new CumQty(0.0),
                    new AvgPx(0.0));
    executionReport.setField(new Text("中文"));
    int seq = session.getStore().getNextSenderMsgSeqNum();
    String message = executionReport.toString();
    List<String> messages = new ArrayList<>();
    session.getStore().set(seq, message);
    session.getStore().get(seq, seq + 1, messages);
    for(String msg : messages) {
       Assert.isTrue(msg.equals(message), "message retrieve from filestore should be equal")
    }
}
```

**Expected behavior**

Message retrieved from filestore should be equal as the one it set to.

**system information:**
 - OS: [e.g. Linux]
 - Java version [e.g. JDK8]
 - QFJ Version [e.g. 2.1.1]

**Additional context**
The problem is that in filestore.java line 366, it use message.length() which is not equal as bytes length when the string is chinese

https://github.com/quickfix-j/quickfixj/blob/ec23c61ff4a10b79946e042b0d5414af31832523/quickfixj-core/src/main/java/quickfix/FileStore.java#L366

**Comment by chrjohn** [comment]
Thanks for the bug report and the reproducer @pyy07 

In line 377 it looks as if the message is correctly stored since `getBytes()` is used:

https://github.com/quickfix-j/quickfixj/blob/ec23c61ff4a10b79946e042b0d5414af31832523/quickfixj-core/src/main/java/quickfix/FileStore.java#L377

Could you confirm that changing line 366 to something like `message.getBytes(CharsetSupport.getCharset()).length` works?

Are you able to provide a PR?

Thanks,
Chris.

**Comment by pyy07** [comment]
yes, message sent/store/log is correct, it only affect when message is retrieved from filestore (when receive resend request)。I am not familiar with the PR process, and haven't done any test with your modification。could you help to fix it? and any workaround is possible?

**Comment by pyy07** [comment]
by changing line 366 
from
final int size = message.length(); 
to 
final int size = message.getBytes(CharsetSupport.getCharset()).length;
solve this problem

**Comment by chrjohn** [comment]
Great, thanks for the update. 👍

**Comment by chnxan** [comment]
Same problem in CachedFileStore.java  344

**Comment by the-thing** [comment]
@chnxan updated the PR. Thanks for pointing that out.
