### ISSUE TITLE
Lower sequence received than expected without PossDup flag. Expected/Received = 445/1110=119

### ISSUE THREAD

**Issue by atlasifs88** [quickfix-j/quickfixj#656]
I am getting this error after restarting FIX.  What QFJ parameters should I set to continue sending orders?

**Comment by chrjohn** [comment]
How is this different from https://github.com/quickfix-j/quickfixj/discussions/599 which you also opened some time ago?

**Comment by atlasifs88** [comment]
The issue occurred when the setting is ResetOnLogon=N after restarting FIX. After changing the value to Y then the issue was resolved.  The setting was set to N because we wanted to have any missed messages to automatically resend the request. 






On Sunday, August 6, 2023, 8:17 AM, Christoph John ***@***.***> wrote:




Closed #656 as not planned.

**Comment by chrjohn** [comment]
When you reset at logon, all messages will be deleted from the store.
When the sequence number is lower than expected then this is a serious error that needs to be resolved manually. The reason for the too low sequence should be investigated.
