### ISSUE TITLE
Could you give me some suggestions for distributed deployment？

### ISSUE THREAD

**Issue by Lorin-github** [quickfix-j/quickfixj#657]
**Is your feature request related to a problem? Please describe.**
I don't know how to do distributed deployment，such as two Initiator service or two Acceptor，Can you give me some advice? thank you

**Describe the solution you'd like**
distributed deployment to ensure high availability

**Describe alternatives you've considered**
no

**Additional context**
As I understand it now, I need to rewrite Session and share messageQueue and make sure that the multiple service are mutually exclusive.

But I think it's wrong，probably should  use 
https://www.quickfixj.org/usermanual/2.3.0/usage/acceptor_failover.html

**Comment by chrjohn** [comment]
You don't need to rewrite Session or other classes. But you need to use a distributed storage.
I think it is better to open a discussion if you have questions regarding this topic.
