### ISSUE TITLE
Resetting a state and writing a message to a `FileStore` causes `IOException`

### ISSUE THREAD

**Issue by krasnyt** [quickfix-j/quickfixj#687]
**Describe the bug**
We act as an acceptor and we are sending execution reports to a client through a "drop copy" session. Sometimes there are bursts of messages, e.g. 15 messages within a couple of millis. We do this even if the counterparty is not connected, they will get what they missed through resend (most of the time they are connected though). The problem comes when the counterparty connects which triggers a state refresh (we see the "Refreshing message/state store on Logon" log message), and at the same time the burst of events is to be sent. 

We use a `FileStore` which on refresh closes all open files (closing the streams) and immediatelly it initializes the cache opening those file streams again to the files. This happens in `initialize(boolean deleteFiles)`. However, if exactly between the time the file streams are closed and reopened comes the message burst, we get these "Stream closed" IOExceptions:

```
java.io.IOException: Stream Closed
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:354)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at java.base/java.io.DataOutputStream.flush(DataOutputStream.java:123)
	at quickfix.FileStore.set(FileStore.java:373)
	at quickfix.SessionState.set(SessionState.java:301)
	at quickfix.Session.persist(Session.java:2563)
	at quickfix.Session.sendRaw(Session.java:2637)
	at quickfix.Session.send(Session.java:2690)
	at quickfix.Session.sendToTarget(Session.java:704)
	at ch.krasny.adapter.inboundfix.InboundFixDropCopySender.sendCopy(InboundFixDropCopySender.java:107)
```

It goes away after few millis when the streams are opened again but the messages that we failed to write to the store are essentially lost.

**To Reproduce**
Reproducing is rather difficult but we managed to reproduce it by sending a lot of messages, e.g. every 10ms to a session and then putting a breakpoint to some place in the `initialize(boolean deleteFiles)` method where the streams are closed and not reopened yet. Get a hit on that breakpoint and resume in e.g. 1s so that the producing code had enough time to send messages. Then in the log you will see these stacktraces.

**Expected behavior**
Writing to a file store when there is an ongoing state reset should not fail. Some synchronization mechanism is probably missing.

**system information:**
 - OS: macOS
 - Java version JDK11
 - QFJ Version 2.3.1

Any other advice? Thank you.

**Comment by krasnyt** [comment]
We understood `RefreshOnLogon` as something that is better to have. What could be the consequence of having it disabled?

**Comment by chrjohn** [comment]
You're welcome.

Here is the relevant part from the docs, for reference: https://github.com/quickfix-j/quickfixj/blob/master/quickfixj-core/src/main/doc/usermanual/usage/acceptor_failover.html
