### ISSUE TITLE
NullPointerException when using `UseDataDictionary=N` and FIXT session

### ISSUE THREAD

**Issue by wajncn** [quickfix-j/quickfixj#776]
**Describe the bug**
Config UseDataDictionary=N,  Throw NullPointException
https://github.com/quickfix-j/quickfixj/pull/775

**system information:**
 - OS: [e.g. Win11]
 - Java version JDK8
 - Quickfix version 5.2SP2

**Comment by chrjohn** [comment]
Good catch.
