### ISSUE TITLE
OnLogon method not getting invoked on resetting the connection

### ISSUE THREAD

**Issue by neerajozha** [quickfix-j/quickfixj#821]
**Describe the bug**
The OnLogon method is not getting invoked on subsequent connection resets

**To Reproduce**
Stop the existing connection with ICE, reconnect with ICE again. If you try to disconnect/reconnect again, the OnLogon method is not getting executed.

**Expected behavior**
The OnLogon method should be executed each time the connection is reset.

**system information:**
Windows
.Net Core

**Comment by chrjohn** [comment]
@neerajozha 
Are you sure this is the right project? ".Net Core" suggests you are using https://github.com/connamara/quickfixn ?
