### ISSUE TITLE
Implement group count validation

### ISSUE THREAD

**Issue by philipwhiuk** [quickfix-j/quickfixj#834]
There's a comment alluding to adding validation for group counts but as far as I can tell it's not implemented.

I'm not sure why the right approach isn't just to check and throw a FieldException if it doesn't match the value expected.

(This could be a toggleable option to avoid making this a breaking change)

https://github.com/quickfix-j/quickfixj/blob/9335f8dc1463d5269e2ff8164565a0525fb84d0c/quickfixj-base/src/main/java/quickfix/Message.java#L793

**Comment by chrjohn** [comment]
https://github.com/quickfix-j/quickfixj/blob/9335f8dc1463d5269e2ff8164565a0525fb84d0c/quickfixj-base/src/main/java/quickfix/DataDictionary.java#L807

Did you mean this or did I misunderstand?

**Comment by philipwhiuk** [comment]
Ah yes, I was confused by the validation essentially being in two places.

**Comment by chrjohn** [comment]
Do you think this could be improved? But probably is no small change...
