### ISSUE TITLE
2.3.1 version  is miss  package of “quickfix.field”

### ISSUE THREAD

**Issue by JohnSimith** [quickfix-j/quickfixj#900]
2.3.1 version  is miss  package of “quickfix.field”

**Comment by chrjohn** [comment]
Which jar file is missing that package? I'd be surprised if it really was missing because it is required by QFJ code pretty much everywhere. 
Please reopen this issue if you have more information. Thank you.

**Comment by JohnSimith** [comment]
![image](https://github.com/user-attachments/assets/54f3e00c-3fbc-407c-83e7-082b6cacd684)
this is code download by https://github.com/quickfix-j/quickfixj/archive/refs/tags/QFJ_RELEASE_2_3_1.zip.

I can`t find this package

**Comment by chrjohn** [comment]
You should get the separate artifacts (core, messages, ...) from Maven central or if you really need the complete distribution then from here https://central.sonatype.com/artifact/org.quickfixj/quickfixj-distribution

The code you downloaded is just the source code. You need to build it first for the fields to be generated.
